import {useEffect,useState,type FormEvent} from 'react';
import {collection,doc,onSnapshot,query,where} from 'firebase/firestore';
import {useNavigate} from 'react-router-dom';
import {call,db} from '../data/firebase';
import {errorMessage} from '../ui/components';
import type {ArenaClass,Student} from '../domain/models';
import '../ui/class-sharing.css';

export function JoinTeacherClass(){
 const [code,setCode]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');const navigate=useNavigate();
 async function join(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{const c=await call<{classId:string;storageUid:string}>('acceptTeacherInvitation',{code});setCode('');navigate(`/ogretmen/siniflar/${c.classId}?owner=${c.storageUid}`);}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}
 return <section className="class-join"><form onSubmit={join}><label>Öğretmen daveti<input aria-label="Öğretmen davet kodu" value={code} onChange={e=>setCode(e.target.value)} placeholder="24 karakterli davet kodu" maxLength={40} required autoComplete="off"/></label><button className="button secondary" disabled={busy}>{busy?'Katılıyor…':'Sınıfa katıl'}</button></form>{error&&<p role="alert" className="error-message">{error}</p>}</section>;
}
type Row={id:string;[key:string]:any};
const labels:Record<string,string>={sharingEnabled:'Ortak yönetim etkinleştirildi',classCreated:'Sınıf oluşturuldu',classUpdated:'Sınıf bilgileri değişti',studentCreated:'Öğrenci eklendi',studentInitialized:'Öğrenci kaydı hazırlandı',studentUpdated:'Öğrenci düzenlendi',studentRemoved:'Öğrenci kaldırıldı',studentCodeRotated:'Kısa kod yenilendi',codeReserved:'Kısa kod ayrıldı',teacherInvited:'Öğretmen daveti oluşturuldu',teacherJoined:'Öğretmen katıldı',teacherRemoved:'Öğretmen erişimi kaldırıldı',invitationRevoked:'Davet iptal edildi',ownershipTransferred:'Sahiplik devredildi',rewardAdjusted:'XP / yıldız değişti',activitySaved:'Etkinlik düzenlendi',classDeletionStarted:'Silme başladı',classDeletionCancelled:'Silme iptal edildi'};
export function ClassSharing({cls,uid}:{cls:ArenaClass;uid:string}){
 const [members,setMembers]=useState<Row[]>([]),[invites,setInvites]=useState<Row[]>([]),[history,setHistory]=useState<Row[]>([]),[activities,setActivities]=useState<Row[]>([]);
 const [code,setCode]=useState(''),[target,setTarget]=useState(''),[confirmName,setConfirmName]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[status,setStatus]=useState('');const navigate=useNavigate();
 const storageUid=cls.storageUid||uid,base=`teachers/${storageUid}/classes/${cls.classId}`;
 useEffect(()=>{setMembers([]);setInvites([]);setHistory([]);setActivities([]);setCode('');const fail=(e:unknown)=>setError(errorMessage(e));const watch=(path:string,put:(r:Row[])=>void)=>onSnapshot(collection(db,path),s=>put(s.docs.map(d=>({id:d.id,...d.data()}))),fail);
 const stops=[watch(`${base}/teacherMembers`,setMembers),watch(`${base}/audit`,setHistory),watch(`${base}/activities`,setActivities),onSnapshot(query(collection(db,'teacherInvitations'),where('storageUid','==',storageUid),where('classId','==',cls.classId)),s=>setInvites(s.docs.map(d=>({id:d.id,...d.data()}))),fail)];return()=>stops.forEach(s=>s());},[base,storageUid,cls.classId]);
 async function work(name:string,data:Record<string,unknown>,success:string){setBusy(true);setError('');setStatus('');try{const result=await call<any>(name,{storageUid,classId:cls.classId,...data});setStatus(success);return result;}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}
 if(cls.status==='deleting')return <section className="class-sharing"><h2>Silme işlemi yarım kaldı</h2><p>Sınıf silme sırasında kilitlendi. Yetkili öğretmen olarak işlemi yeniden başlatabilirsin.</p><button className="button danger" disabled={busy} onClick={()=>void work(cls.deletionToken?'deleteClass':'permanentlyDeleteClass',{confirmName:cls.className},'Silme tamamlandı.').then(v=>v&&navigate('/ogretmen/siniflar'))}>{busy?'İşlem sürüyor…':'Silme işlemini sürdür'}</button><p role="alert" className="error-message">{error}</p></section>;
 return <section className="class-sharing" aria-label="Ortak sınıf yönetimi"><h2>Ortak sınıf yönetimi</h2><p>Tüm yetkili öğretmenler aynı öğrenci verilerini yönetir. Kurucu ve davetle katılan aktif öğretmenler tam yönetim yetkisine sahiptir.</p><p role="alert" className="error-message">{error}</p><p role="status" className="status-message">{status}</p>
 <section><h3>Öğretmenler</h3><ul className="sharing-rows">{members.filter(m=>m.status==='active').map(m=><li key={m.id}><span>{m.email}{m.uid===(cls.ownerUid||storageUid)&&<small> · Sınıf sahibi</small>}</span>{m.uid!==(cls.ownerUid||storageUid)&&m.uid!==(cls.createdBy||storageUid)&&<button className="text-button danger-text" disabled={busy} onClick={()=>void work('removeClassTeacher',{teacherUid:m.uid},'Öğretmenin erişimi kaldırıldı. Sınıf verileri korundu.')}>Erişimi kaldır</button>}</li>)}</ul><button className="button secondary" disabled={busy} onClick={()=>void work('inviteTeacher',{},'Davet 24 saat geçerli ve tek kullanımlı.').then(v=>v&&setCode(v.code))}>Öğretmen davet et</button>{code&&<div className="invitation-code"><label>Davet kodu<output>{code}</output></label><button className="text-button" onClick={()=>void navigator.clipboard.writeText(code).then(()=>setStatus('Davet kodu kopyalandı.')).catch(()=>setError('Kod kopyalanamadı.'))}>Kopyala</button><p>Kodu davet edeceğin öğretmene paylaş. Bu ekrandan ayrıldıktan sonra kod tekrar gösterilmez.</p></div>}
 <ul className="sharing-rows">{invites.filter(i=>!i.revoked&&!i.consumedBy&&i.createdAt?.toMillis()+86400000>Date.now()).map(i=><li key={i.id}><span>Bekleyen davet · {new Date(i.createdAt.toMillis()+86400000).toLocaleString('tr-TR')} tarihine kadar</span><button className="text-button" disabled={busy} onClick={()=>void work('revokeTeacherInvitation',{invitationId:i.id},'Davet iptal edildi.')}>İptal et</button></li>)}</ul></section>
 <section><h3>Sınıf bilgileri</h3><p>Sınıf adını, türünü ve kademelerini üstteki <strong>Sınıfı düzenle</strong> düğmesinden güncelleyebilirsin.</p></section>
 <section><h3>Etkinlikler ve yarışmalar</h3><form onSubmit={e=>{e.preventDefault();const form=e.currentTarget,f=new FormData(form);void work('saveClassActivity',{title:f.get('title'),status:'planned'},'Etkinlik oluşturuldu.').then(v=>v&&form.reset());}}><label>Etkinlik / Yarışma adı<input name="title" required maxLength={100}/></label><button className="button secondary" disabled={busy}>Oluştur</button></form><ul className="sharing-rows">{activities.map(a=><li key={a.id}><span>{a.title}</span><select aria-label={`${a.title} durumu`} disabled={busy} value={a.status} onChange={e=>void work('saveClassActivity',{activityId:a.id,title:a.title,status:e.target.value},'Etkinlik güncellendi.')}><option value="planned">Planlandı</option><option value="active">Aktif</option><option value="completed">Tamamlandı</option><option value="cancelled">İptal edildi</option></select></li>)}</ul></section>
 {<section><h3>Sahipliği devret</h3><p>Sahiplik bilgisi güncellenir. Sınıfı oluşturan öğretmenin ve aktif üyelerin yönetim yetkisi korunur.</p><form onSubmit={e=>{e.preventDefault();void work('transferClassOwnership',{teacherUid:target},'Sahiplik devredildi.');}}><label>Yeni sınıf sahibi<select required value={target} onChange={e=>setTarget(e.target.value)}><option value="">Öğretmen seç</option>{members.filter(m=>m.status==='active'&&m.uid!==uid).map(m=><option key={m.id} value={m.uid}>{m.email}</option>)}</select></label><button className="button secondary" disabled={busy||!target}>Sahipliği devret</button></form></section>}
 <section><h3>İşlem geçmişi</h3><ol className="sharing-history">{[...history].sort((a,b)=>(b.at?.toMillis()||0)-(a.at?.toMillis()||0)).slice(0,100).map(a=><li key={a.id}><strong>{labels[a.operation]||a.operation}</strong><span>{a.actorEmail} · {a.at?.toDate().toLocaleString('tr-TR')}</span>{a.operation==='rewardAdjusted'&&<small>{a.changes.amount>0?'+':''}{a.changes.amount} {a.changes.kind==='xp'?'XP':'yıldız'} · {a.changes.reason}</small>}</li>)}</ol></section>
 {<details className="sharing-danger"><summary>Sınıfı ve verilerini kalıcı sil</summary><p>Öğrenciler, kısa kodlar ve çalışma geçmişleri kalıcı olarak silinir. Onaylamak için <strong>{cls.className}</strong> adını yaz.</p><form onSubmit={e=>{e.preventDefault();void work('permanentlyDeleteClass',{confirmName},'Sınıf kalıcı silindi.').then(v=>v&&navigate('/ogretmen/siniflar'));}}><label>Sınıf adı<input value={confirmName} onChange={e=>setConfirmName(e.target.value)} required autoComplete="off"/></label><button className="button danger" disabled={busy||confirmName!==cls.className}>Kalıcı silmeyi onayla</button></form></details>}
 </section>;
}
export function StudentReward({student}:{student:Student}){
 const [open,setOpen]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[status,setStatus]=useState('');
 const [balance,setBalance]=useState<{totalXP:number;academicXP:number;stars:number}>();
 useEffect(()=>{setBalance(undefined);if(!open)return;return onSnapshot(doc(db,`teachers/${student.teacherUid}/students/${student.studentId}/learning/summary`),s=>{const v=s.data();if(v)setBalance({totalXP:v.totalXP||0,academicXP:v.academicXP??v.totalXP??0,stars:v.stars||0});},e=>setError(errorMessage(e)));},[open,student.teacherUid,student.studentId]);
 return <><button onClick={()=>{setOpen(true);setError('');setStatus('');}}>XP / yıldız</button>{open&&<div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-label="XP / yıldız düzenle"><button className="modal-close" aria-label="Kapat" disabled={busy} onClick={()=>setOpen(false)}>×</button><h2>{student.firstName} · XP / yıldız</h2>{balance&&<p>Toplam: <strong>{balance.totalXP} XP</strong> · Akademik: {balance.academicXP} XP · <strong>{balance.stars} yıldız</strong></p>}<p>Verme için pozitif, geri alma için negatif sayı gir. Akademik XP ve soru kazanımları korunur.</p><form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);setError('');try{await call('adjustStudentReward',{storageUid:student.teacherUid,classId:student.classId,studentId:student.studentId,kind:f.get('kind'),amount:Number(f.get('amount')),reason:f.get('reason')});setStatus('Değişiklik kaydedildi.');}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}}><label>Ödül<select name="kind" aria-label="Ödül"><option value="xp">XP</option><option value="stars">Yıldız</option></select></label><label>Değişim<input name="amount" type="number" step="1" min={-10000} max={10000} required/></label><label>Neden<input name="reason" maxLength={300} required/></label><button className="button primary" disabled={busy}>Kaydet</button></form><p role="alert" className="error-message">{error}</p><p role="status" className="status-message">{status}</p></section></div>}</>;
}
