import {useEffect,useState,type FormEvent} from 'react';
import {Link,useSearchParams} from 'react-router-dom';
import {call} from '../data/firebase';
import {useSession} from '../app/Session';
import {errorMessage} from '../ui/components';
import {MathVisual} from '../ui/MathVisual';
import {QuestionReport} from './QuestionReport';
import {reportStatuses} from '../../shared/question-bank.mjs';
import '../ui/question-bank.css';
type RecordRow={question:any;answer:any};
type Bank={permissions:{canManage:boolean};curriculum:any;records:RecordRow[]};
export function QuestionBankNav(){
 const {user}=useSession(),[manager,setManager]=useState(false);
 useEffect(()=>{let alive=true;if(user)void call<{canManage:boolean}>('teacherBankPermissions',{}).then(v=>{if(alive)setManager(v.canManage);}).catch(()=>{if(alive)setManager(false);});return()=>{alive=false;};},[user?.uid]);
 return <>{manager&&<Link to="/ogretmen/soru-hatalari">Soru Hata Bildirimleri</Link>}</>;
}
function QuestionBody({row,selected,onPick,reveal}:{row:RecordRow;selected?:string;onPick?:(id:string)=>void;reveal:boolean}){
 const q=row.question,a=row.answer;
 return <><QuestionReport key={q.questionId} questionId={q.questionId}/>{q.content&&<p className="question-content">{q.content}</p>}{q.visual&&q.visualPlacement==='above'&&<MathVisual visual={q.visual}/>}<h2 className="question-text" data-question-id={q.questionId}>{q.questionText}</h2>{q.visual&&q.visualPlacement!=='above'&&<MathVisual visual={q.visual}/>}<div className="answer-choices">{q.choices.map((c:any,i:number)=><button key={c.choiceId} disabled={!onPick} aria-pressed={selected===c.choiceId} className={reveal&&c.choiceId===a?.correctOptionId?'choice-correct':''} onClick={()=>onPick?.(c.choiceId)}><span>{'ABCDEF'[i]}</span>{c.visual&&<MathVisual visual={c.visual}/>}<strong>{c.text}</strong></button>)}</div>{reveal&&<div className="bank-answer"><strong>Doğru cevap: {a?.correctOptionId||'Cevap kaydı bulunamadı'}</strong><p>{a?.explanation||'Bu soru için açıklama eklenmemiş.'}</p></div>}</>;
}
export function TeacherQuestionBank(){
 const [search,setSearch]=useSearchParams(),[grade,setGrade]=useState(2),[subject,setSubject]=useState(''),[unit,setUnit]=useState(''),[bank,setBank]=useState<Bank>(),[active,setActive]=useState<string>(''),[selected,setSelected]=useState<string[]>([]);
 const [mode,setMode]=useState<'review'|'test'|'result'>('review'),[test,setTest]=useState<RecordRow[]>([]),[index,setIndex]=useState(0),[answers,setAnswers]=useState<Record<string,string>>({});
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[status,setStatus]=useState(''),[revision,setRevision]=useState(0),[editor,setEditor]=useState<RecordRow|null>(null),[creating,setCreating]=useState(false),[deleting,setDeleting]=useState<RecordRow|null>(null);
 useEffect(()=>{let alive=true;setBusy(true);setError('');setBank(undefined);setActive('');setSelected([]);setMode('review');void call<Bank>('teacherQuestionBank',{grade}).then(v=>{if(!alive)return;setBank(v);setSubject(s=>v.curriculum?.subjects.some((x:any)=>x.id===s)?s:v.curriculum?.subjects.find((x:any)=>v.records.some(r=>r.question.subject===x.id&&r.question.status==='published'))?.id||v.curriculum?.subjects[0]?.id||'');}).catch(e=>{if(alive)setError(errorMessage(e));}).finally(()=>{if(alive)setBusy(false);});return()=>{alive=false;};},[grade,revision]);
 useEffect(()=>{let alive=true;const id=search.get('question');if(id)void call<RecordRow>('getBankQuestion',{questionId:id}).then(r=>{if(!alive||!r.question)return;if(r.question.gradeLevel!==grade){setGrade(r.question.gradeLevel);return;}setSubject(r.question.subject);setUnit(r.question.unitId);setActive(id);}).catch(e=>{if(alive)setError(errorMessage(e));});return()=>{alive=false;};},[search,grade,bank]);
 const subjects=bank?.curriculum?.subjects||[],units=subjects.find((s:any)=>s.id===subject)?.units||[];
 const rows=(bank?.records||[]).filter(r=>r.question.status==='published'&&(!subject||r.question.subject===subject)&&(!unit||r.question.unitId===unit));
 const row=bank?.records.find(r=>r.question.questionId===active)||rows[0],manager=bank?.permissions.canManage;
 async function work(task:()=>Promise<void>){setBusy(true);setError('');setStatus('');try{await task();}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}
 function chooseGrade(g:number){setSearch({});setGrade(g);setUnit('');setSubject('');}
 function start(){const chosen=rows.filter(r=>selected.length?selected.includes(r.question.questionId):true).slice(0,50);if(!chosen.length)return;setTest(chosen);setIndex(0);setAnswers({});setMode('test');}
 function newQuestion(){const s=subjects.find((s:any)=>s.id===subject),u=units.find((u:any)=>u.id===unit)||units[0];if(!u){setError('Soru eklemek için mevcut bir ders ve ünite seç.');return;}setCreating(true);setEditor({question:{questionId:crypto.randomUUID(),gradeLevel:grade,subject:s.id,unitId:u.id,topic:u.topics?.[0]?.id||u.id,questionText:'',choices:['A','B','C','D'].map(choiceId=>({choiceId,text:''}))},answer:{correctOptionId:'A',explanation:''}});}
 async function save(record:RecordRow){await work(async()=>{await call('manageQuestionBank',{operation:creating?'create':'update',grade,record,expectedRevision:editor?.question.bankRevision||0});setEditor(null);setRevision(v=>v+1);setStatus('Soru bankası güncellendi. Açık öğrenci testleri ve geçmiş sonuçlar korundu.');});}
 return <section className="teacher-question-bank"><p>İnceleme ve öğretmen testleri öğrenci istatistiklerini, sıralamasını veya XP’sini etkilemez.</p>
  {error&&<p role="alert" className="error-message">{error}</p>}{status&&<p role="status" className="status-message">{status}</p>}
  {mode==='review'&&<><div className="bank-filters"><label>Kademe<select value={grade} disabled={busy} onChange={e=>chooseGrade(Number(e.target.value))}>{Array.from({length:12},(_,i)=>i+1).map(g=><option key={g} value={g}>{g}. Sınıf</option>)}</select></label><label>Ders<select value={subject} disabled={busy} onChange={e=>{setSearch({});setSubject(e.target.value);setUnit('');setActive('');setSelected([]);}}>{subjects.map((s:any)=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Ünite<select value={unit} disabled={busy} onChange={e=>{setSearch({});setUnit(e.target.value);setActive('');setSelected([]);}}><option value="">Tüm üniteler</option>{units.map((u:any)=><option key={u.id} value={u.id}>{u.displayName||u.name}</option>)}</select></label></div>
   <div className="bank-toolbar"><strong>İnceleme Modu · {rows.length} soru</strong><button className="button primary" disabled={busy||!rows.length} onClick={start}>Test Modu · {Math.min(selected.length||rows.length,50)} soruyu çöz</button>{manager&&<><button className="button secondary" disabled={busy} onClick={newQuestion}>Soru ekle</button><label className="bank-upload">JSON soru bankası yükle<input type="file" accept=".json,application/json" disabled={busy||!bank?.curriculum} onChange={e=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;void work(async()=>{if(file.size>2000000)throw Error('JSON en fazla 2 MB olabilir.');const value=JSON.parse(await file.text());const r=await call<{changed:number}>('manageQuestionBank',{operation:'import',grade,bank:value});setStatus(`${r.changed} yeni soru eklendi. Mevcut sorular korundu.`);setRevision(v=>v+1);});}}/></label><details><summary>JSON örneği</summary><p>Bir yüklemede en fazla 50 yeni soru. Mevcut ID’ler üzerine yazılmaz. Seçilen kademenin mevcut ders/ünite/konu kimliklerini kullan.</p><pre>{JSON.stringify([{question:{questionId:'yeni-soru-id',gradeLevel:grade,subject,unitId:unit||units[0]?.id,topic:units[0]?.topics?.[0]?.id||units[0]?.id,questionText:'Soru metni',choices:['A','B','C','D'].map(choiceId=>({choiceId,text:`${choiceId} seçeneği`}))},answer:{correctOptionId:'A',explanation:'Çözüm açıklaması'}}],null,2)}</pre></details></>}</div>
   {busy&&!bank&&<p role="status">Soru bankası yükleniyor…</p>}{!busy&&!rows.length&&<p>Bu seçimde yayımlanmış soru yok. Diğer dersleri veya kademeleri seçebilirsin.</p>}
   <div className="bank-workspace"><ul className="bank-question-list">{rows.map((r,i)=><li key={r.question.questionId}><label><input type="checkbox" checked={selected.includes(r.question.questionId)} disabled={!selected.includes(r.question.questionId)&&selected.length>=50} onChange={e=>setSelected(e.target.checked?[...selected,r.question.questionId]:selected.filter(id=>id!==r.question.questionId))}/><span className="sr-only">{i+1}. soruyu teste ekle</span></label><button aria-current={row?.question.questionId===r.question.questionId?'true':undefined} onClick={()=>{setSearch({});setActive(r.question.questionId);}}>{i+1}. {r.question.questionText.slice(0,90)}</button></li>)}</ul>{row&&<article className="bank-question"><small>{row.question.questionId} · {row.question.unitName} {row.question.status==='archived'&&'· Yeni testlerden kaldırıldı'}</small><QuestionBody row={row} reveal/>{manager&&<div className="bank-toolbar"><button className="button secondary" disabled={busy} onClick={()=>{setCreating(false);setEditor(row);}}>Soruyu düzenle</button><button className="text-button danger-text" disabled={busy||row.question.status==='archived'} onClick={()=>setDeleting(row)}>Soruyu sil</button></div>}</article>}</div></>}
  {mode==='test'&&test[index]&&<article className="bank-question"><div className="bank-toolbar"><h2>Test Modu · {index+1} / {test.length}</h2><button className="text-button" onClick={()=>setMode('review')}>İncelemeye dön</button></div><QuestionBody row={test[index]} selected={answers[test[index].question.questionId]} onPick={choice=>setAnswers(v=>({...v,[test[index].question.questionId]:choice}))} reveal={false}/><div className="bank-toolbar"><button className="button secondary" disabled={!index} onClick={()=>setIndex(v=>v-1)}>Önceki soru</button>{index<test.length-1?<button className="button primary" onClick={()=>setIndex(v=>v+1)}>Sonraki soru</button>:<button className="button primary" onClick={()=>setMode('result')}>Sonuçları gör</button>}</div></article>}
  {mode==='result'&&<section className="bank-test-result"><h2>Öğretmen test sonucu</h2><p>{test.filter(r=>answers[r.question.questionId]===r.answer?.correctOptionId).length} doğru · {test.filter(r=>answers[r.question.questionId]&&answers[r.question.questionId]!==r.answer?.correctOptionId).length} yanlış · {test.filter(r=>!answers[r.question.questionId]).length} boş</p><p>Bu sonuç yalnız senin incelemen içindir; öğrenci XP ve sıralamaları değişmedi.</p><button className="button secondary" onClick={()=>setMode('review')}>İnceleme Moduna dön</button>{test.map(r=><details key={r.question.questionId}><summary>{r.question.questionText} · {answers[r.question.questionId]||'Boş'}</summary><QuestionBody row={r} reveal/></details>)}</section>}
  {editor&&<QuestionEditor row={editor} busy={busy} creating={creating} save={save} close={()=>setEditor(null)} error={error} curriculum={bank?.curriculum}/>}
  {deleting&&<div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-label="Soruyu sil"><h2>Soruyu yeni testlerden kaldır</h2><p>Soru ID’si, açık testler ve geçmiş sonuçlar korunur. Bu soru yeni öğrenci testlerinde görünmez.</p><button className="button secondary" disabled={busy} onClick={()=>setDeleting(null)}>Vazgeç</button><button className="button danger" disabled={busy} onClick={()=>void work(async()=>{await call('manageQuestionBank',{operation:'delete',grade,questionId:deleting.question.questionId});setDeleting(null);setRevision(v=>v+1);setStatus('Soru yeni testlerden kaldırıldı. Geçmiş korundu.');})}>Silmeyi onayla</button>{error&&<p role="alert">{error}</p>}</section></div>}
 </section>;
}
function QuestionEditor({row,busy,creating,save,close,error,curriculum}:{row:RecordRow;busy:boolean;creating:boolean;save:(r:RecordRow)=>Promise<void>;close:()=>void;error:string;curriculum:any}){
 const [value,setValue]=useState<RecordRow>(()=>structuredClone(row)),[presentation,setPresentation]=useState(()=>JSON.stringify({...Object.fromEntries(['visual','visualPlacement','content'].filter(k=>k in row.question).map(k=>[k,row.question[k]])),...(row.question.choices.some((c:any)=>c.visual)?{choiceVisuals:row.question.choices.map((c:any)=>c.visual||null)}:{})},null,2)),[localError,setLocalError]=useState(''); const topics=curriculum?.subjects.find((s:any)=>s.id===value.question.subject)?.units.find((u:any)=>u.id===value.question.unitId)?.topics||[];
 function submit(e:FormEvent){e.preventDefault();try{const question={...value.question};const parsed=JSON.parse(presentation);if(parsed.visual)question.visual=parsed.visual;else delete question.visual;if(parsed.visualPlacement)question.visualPlacement=parsed.visualPlacement;else delete question.visualPlacement;if('choiceVisuals' in parsed){if(!Array.isArray(parsed.choiceVisuals)||parsed.choiceVisuals.length!==question.choices.length)throw Error('options');question.choices=question.choices.map((c:any,i:number)=>{const next={...c};if(parsed.choiceVisuals[i])next.visual=parsed.choiceVisuals[i];else delete next.visual;return next;});}if(parsed.content)question.content=parsed.content;else delete question.content;void save({...value,question});setLocalError('');}catch{setLocalError('Görsel / okuma metni JSON biçimi geçersiz.');}}
 return <div className="modal-backdrop"><section className="modal bank-editor" role="dialog" aria-modal="true" aria-label={creating?'Soru ekle':'Soruyu düzenle'}><button className="modal-close" aria-label="Kapat" disabled={busy} onClick={close}>×</button><h2>{creating?'Soru ekle':'Soruyu düzenle'}</h2><p>{value.question.gradeLevel}. Sınıf · Soru ID: {value.question.questionId}</p><form onSubmit={submit}>{topics.length>0&&<label>Konu<select value={value.question.topic} onChange={e=>setValue(v=>({...v,question:{...v.question,topic:e.target.value},answer:{...v.answer,outcomeCode:undefined,outcomeId:undefined,candidateOutcomeCodes:undefined}}))}>{topics.map((t:any)=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label>}<label>Soru metni<textarea required rows={4} maxLength={6000} value={value.question.questionText} onChange={e=>setValue(v=>({...v,question:{...v.question,questionText:e.target.value}}))}/></label>{value.question.choices.map((c:any,i:number)=><label key={c.choiceId}>{c.choiceId} seçeneği<input value={c.text} required={!c.visual} maxLength={4000} onChange={e=>setValue(v=>({...v,question:{...v.question,choices:v.question.choices.map((x:any,j:number)=>j===i?{...x,text:e.target.value}:x)}}))}/></label>)}<label>Doğru cevap<select value={value.answer.correctOptionId} onChange={e=>setValue(v=>({...v,answer:{...v.answer,correctOptionId:e.target.value}}))}>{value.question.choices.map((c:any)=><option key={c.choiceId}>{c.choiceId}</option>)}</select></label><label>Açıklama<textarea rows={3} maxLength={6000} value={value.answer.explanation} onChange={e=>setValue(v=>({...v,answer:{...v.answer,explanation:e.target.value}}))}/></label><details><summary>Görsel ve okuma metni</summary><label>Sunum JSON<textarea rows={6} value={presentation} onChange={e=>setPresentation(e.target.value)}/></label><p>Desteklenen görsel sözleşmesi kullanılır. Boş nesne görseli kaldırır.</p></details>{localError&&<p role="alert">{localError}</p>}<button className="button primary" disabled={busy}>{busy?'Yayımlanıyor…':'Soruyu kaydet'}</button></form>{error&&<p role="alert" className="error-message">{error}</p>}</section></div>;
}
export function QuestionReports(){
 const [rows,setRows]=useState<any[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[filter,setFilter]=useState('all');
 async function load(){setBusy(true);setError('');try{setRows(await call<any[]>('questionReports',{}));}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}
 useEffect(()=>{void load();},[]);
 const groups=new Map<string,any[]>();for(const r of rows.filter(r=>filter==='all'||r.status===filter)){const group=groups.get(r.questionId)||[];group.push(r);groups.set(r.questionId,group);}
 return <section className="question-reports"><div className="bank-toolbar"><label>Bildirim durumu<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">Tüm durumlar</option>{Object.entries(reportStatuses).map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label><button className="button secondary" disabled={busy} onClick={()=>void load()}>Yenile</button></div>{error&&<p role="alert" className="error-message">{error}</p>}{busy&&<p role="status">Bildirimler yükleniyor…</p>}{!busy&&!error&&!groups.size&&<p>Bu durumda bildirim yok.</p>}{[...groups].map(([id,list])=><section className="report-group" key={id}><h2>{list[0].gradeLevel}. Sınıf · {list[0].subjectName} · {list[0].unitName}</h2><p>{id} · {list.length} bildirim</p><Link className="button secondary" to={`/ogretmen/soru-bankasi?question=${encodeURIComponent(id)}`}>Soruyu aç</Link><ul>{list.sort((a,b)=>(b.createdAt?.toMillis()||0)-(a.createdAt?.toMillis()||0)).map(r=><li key={r.id}><strong>{r.type}</strong><p>{r.description||'Ek açıklama yok.'}</p><small>{r.reporterRole==='student'?'Öğrenci':'Öğretmen'} · {r.reporterUid} · {r.createdAt?.toDate().toLocaleString('tr-TR')}</small><label>Durum<select aria-label={`${r.id} bildirim durumu`} value={r.status} disabled={busy} onChange={e=>{const status=e.target.value;setBusy(true);setError('');void call('updateQuestionReport',{reportId:r.id,status}).then(()=>setRows(v=>v.map(x=>x.id===r.id?{...x,status}:x))).catch(e=>setError(errorMessage(e))).finally(()=>setBusy(false));}}>{Object.entries(reportStatuses).map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label></li>)}</ul></section>)}</section>;
}
