import { useEffect, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { call } from '../data/firebase';
import { errorMessage } from '../ui/components';
import { number, percent, sortStudents, type AnalyticsReport, type AnalyticsStudent, type Dimension, type Period, type Performance } from '../domain/analytics';

function Metrics({ data, period, students }: { data: Performance; period: Period; students?: number }) {
  const c = data[period];
  return <dl className="analytics-metrics">{students !== undefined && <div><dt>Öğrenci</dt><dd>{number(students)}</dd></div>}<div><dt>Çözülen soru</dt><dd>{number(c.solved)}</dd></div><div><dt>Doğru / Yanlış</dt><dd>{number(c.correct)} <small>/ {number(c.wrong)}</small></dd></div><div><dt>Başarı</dt><dd className={!c.solved ? 'no-data' : ''}>{percent(c)}</dd></div><div><dt>Academic XP · Genel</dt><dd>{number(data.academicXP)}</dd></div><div><dt>Academic XP · Bu hafta</dt><dd>{number(data.weeklyAcademicXP)}</dd></div></dl>;
}
function PerformanceRows({ dimensions, period, kind }: { dimensions: Dimension[]; period: Period; kind: 'subject' | 'topic' }) {
  const rows = dimensions.filter(d => d.kind === kind && d[period].solved).sort((a,b) => a.gradeLevel-b.gradeLevel || a.subjectName.localeCompare(b.subjectName,'tr') || (a.topicName || '').localeCompare(b.topicName || '', 'tr'));
  return rows.length ? <div className="dimension-list">{rows.map(d => <article key={`${d.gradeLevel}_${d.subject}_${d.topic || ''}`}><div><h3>{kind === 'topic' ? d.topicName : d.subjectName}</h3><span>{d.gradeLevel}. Sınıf{kind === 'topic' && ` · ${d.subjectName}`}</span></div><div className="dimension-volume"><strong>{number(d[period].solved)} soru</strong><span>{number(d[period].correct)} doğru · {number(d[period].wrong)} yanlış</span></div><div className="dimension-rate"><b>{percent(d[period])}</b><progress aria-label={`${d.topicName || d.subjectName} başarı oranı`} value={d[period].correct} max={d[period].solved}/></div></article>)}</div> : <p className="analytics-empty">Bu dönemde kabul edilmiş cevap yok. Başarı oranı henüz hesaplanamaz.</p>;
}
function StudentTable({ students, period }: { students: AnalyticsStudent[]; period: Period }) {
  const navigate = useNavigate();
  return students.length ? <table className="analytics-table"><caption className="visually-hidden">Öğrenci performansı; çalışma miktarı, başarı ve XP ayrı ölçütlerdir.</caption><thead><tr>{['Öğrenci','Kademe','Soru','Doğru','Yanlış','Başarı','Academic XP','Haftalık XP','Arena sırası'].map(h => <th key={h} scope="col">{h}</th>)}</tr></thead><tbody>{students.map(s => <tr key={s.studentId} data-analytics-student={s.studentId}><td><button className="analytics-name" onClick={() => navigate('/ogretmen/ogrenciler/' + s.studentId)}>{s.displayName}</button><small>{s.className}<span className="compact-grade"> · {s.gradeLevel}. Sınıf</span></small><span className="compact-rank">#{period === 'overall' ? s.overallRank : s.weeklyRank}</span></td><td data-label="Kademe">{s.gradeLevel}. Sınıf</td><td data-label="Soru">{number(s[period].solved)}</td><td data-label="Doğru">{number(s[period].correct)}</td><td data-label="Yanlış">{number(s[period].wrong)}</td><td data-label="Başarı">{percent(s[period])}</td><td data-label="Academic XP">{number(s.academicXP)}</td><td data-label="Haftalık XP">{number(s.weeklyAcademicXP)}</td><td data-label="Arena sırası">#{period === 'overall' ? s.overallRank : s.weeklyRank}<small>{s.className} · {period === 'overall' ? 'Genel' : 'Bu hafta'}</small></td></tr>)}</tbody></table> : <p className="analytics-empty">Bu görünümde öğrenci yok.</p>;
}
function LeaderList({ students, label, value, emptyText = "Bu hafta kabul edilmiş cevap yok." }: { students: AnalyticsStudent[]; label: string; value: (s: AnalyticsStudent) => string; emptyText?: string }) {
  return <section><h3>{label}</h3>{students.length ? <ol className="analytics-leaders">{students.map(s => <li key={s.studentId}><Link to={'/ogretmen/ogrenciler/' + s.studentId}>{s.displayName}<small>{s.className}</small></Link><strong>{value(s)}</strong></li>)}</ol> : <p className="analytics-empty">{emptyText}</p>}</section>;
}

export function TeacherAnalytics({ view, uid, classId, studentId, revision, classSection }: { view: 'home' | 'students' | 'analytics' | 'detail'; uid: string; classId?: string; studentId?: string; revision: string; classSection?: 'overview' | 'analysis' }) {
  const [report, setReport] = useState<AnalyticsReport>(), [error, setError] = useState(''), [loading, setLoading] = useState(true), [refresh, setRefresh] = useState(0);
  const [period, setPeriod] = useState<Period>('overall'), [tab, setTab] = useState('general'), [filter, setFilter] = useState(''), [sort, setSort] = useState('most');
  useEffect(() => {
    let current = true; setLoading(true); setError(''); setReport(undefined);
    void call<AnalyticsReport>('teacherAnalytics', { ...(classId ? { classId } : {}), ...(studentId ? { studentId } : {}) }).then(data => { if (current) setReport(data); }).catch(e => { if (current) setError(errorMessage(e)); }).finally(() => { if (current) setLoading(false); });
    return () => { current = false; };
  }, [uid, classId, studentId, refresh, revision]);
  useEffect(() => { setTab('general'); setFilter(''); }, [classId, studentId]);
  if (loading) return <section className="teacher-analytics"><p role="status">Performans özeti hazırlanıyor…</p></section>;
  if (error || !report) return <section className="teacher-analytics"><p role="alert">{error || 'Rapor yüklenemedi.'}</p><button className="button secondary" onClick={() => setRefresh(v => v+1)}>Yeniden dene</button></section>;
  const cls = report.classes.find(c => c.classId === classId), student = report.students.find(s => s.studentId === studentId);
  const scoped = report.students.filter(s => (!classId || s.classId === classId) && (!studentId || s.studentId === studentId));
  const visible = sortStudents(scoped.filter(s => !filter || s.classId === filter), sort, period);
  const metrics = student || cls || report.totals;
  const active = [...scoped].filter(s => s.weekly.solved > 0).sort((a,b) => b.weekly.solved-a.weekly.solved || a.displayName.localeCompare(b.displayName,'tr')).slice(0,3);
  const arenaScore = period === 'overall' ? 'academicXP' : 'weeklyAcademicXP', arenaRank = period === 'overall' ? 'overallRank' : 'weeklyRank';
  const arena = [...scoped].filter(s => s[arenaScore] > 0 && s[arenaRank] === 1).sort((a,b) => a.className.localeCompare(b.className,'tr') || a.displayName.localeCompare(b.displayName,'tr'));
  const support = scoped.filter(s => s.signals.length);
  const sectionTab = classSection === 'overview' ? 'general' : classSection === 'analysis' && tab === 'general' ? 'subjects' : tab;
  return <section className="teacher-analytics" aria-label="Öğretmen performans raporu">
    <div className="analytics-toolbar"><div className="analytics-period" aria-label="Rapor dönemi"><button aria-pressed={period === 'overall'} onClick={() => setPeriod('overall')}>Genel</button><button aria-pressed={period === 'weekly'} onClick={() => setPeriod('weekly')}>Bu hafta</button></div><span>{report.weekKey} · İstanbul</span><button className="text-button" onClick={() => setRefresh(v => v+1)}>Verileri yenile</button></div>
    <p className="analytics-definition">Soru: çalışma miktarı · Başarı: doğru / tüm cevaplar · XP: oyunlaştırılmış ilerleme</p>
    {student && <header className="analytics-identity"><Link className="back-link" to={'/ogretmen/siniflar/' + student.classId}>← {student.className}</Link><h2>{student.displayName}</h2><p>{student.className} · {student.gradeLevel}. Sınıf · Arena #{period === 'overall' ? student.overallRank : student.weeklyRank} ({period === 'overall' ? 'Genel' : 'Bu hafta'})</p></header>}
    {view === 'home' && <dl className="analytics-kpis"><div><dt>Toplam sınıf</dt><dd>{number(report.totals.classCount)}</dd></div><div><dt>Toplam öğrenci</dt><dd>{number(report.totals.studentCount)}</dd></div><div><dt>Çözülen soru</dt><dd data-testid="dashboard-solved">{number(report.totals[period].solved)}</dd></div><div><dt>Genel başarı · {period === 'overall' ? 'Tüm zamanlar' : 'Bu hafta'}</dt><dd data-testid="dashboard-accuracy">{percent(report.totals[period])}</dd></div></dl>}
    {(student || cls && classSection !== 'analysis') && <Metrics data={metrics} period={period} students={cls?.studentCount}/>}
    {(student || cls && classSection === 'analysis') && <nav className="analytics-tabs" aria-label="Performans bölümleri">{[...(!classSection ? [['general','Genel']] : []),['subjects','Dersler'],['topics','Konular']].map(([key,label]) => <button key={key} aria-pressed={sectionTab === key} onClick={() => setTab(key)}>{label}</button>)}</nav>}
    {view === 'home' && <><div className="analytics-section-heading"><h2>Sınıf performansı</h2><span>Mevcut üyelerin verileri</span></div><div className="analytics-classes">{report.classes.map(c => <Link key={c.classId} to={'/ogretmen/siniflar/' + c.classId}><h3>{c.className} <span>→</span></h3><p>Varsayılan kademe: {c.defaultGradeLevel}. Sınıf · {c.studentCount} öğrenci</p><div><b>{number(c[period].solved)} soru</b><b>{percent(c[period])}</b><span>Bu hafta {number(c.weeklyAcademicXP)} Academic XP</span></div></Link>)}</div>{!report.classes.length && <p className="analytics-empty">Henüz sınıf yok. İlk sınıfını oluşturabilirsin.</p>}</>}
    {!student && sectionTab === 'general' && view !== 'analytics' && <><div className="analytics-leader-grid"><LeaderList label="Bu haftanın en aktifleri" students={active} value={s => `${number(s.weekly.solved)} soru`}/><LeaderList label={`Sınıfların Arena liderleri · ${period === "overall" ? "Genel" : "Bu hafta"}`} students={arena} emptyText="Bu dönemde kazanılmış Academic XP yok." value={s => `${number(s[arenaScore])} XP · #${s[arenaRank]}`}/></div><section className="analytics-support"><h3>Desteğe ihtiyaç duyabilecek öğrenciler</h3><p className="field-hint">Açıklanabilir sinyaller; tanı veya akademik başarı sıralaması değildir. Başarı sinyali için en az 20 cevap gerekir.</p>{support.length ? <ul>{support.map(s => <li key={s.studentId}><Link to={'/ogretmen/ogrenciler/' + s.studentId}>{s.displayName}</Link><span>{number(s.overall.solved)} soru · {percent(s.overall)} · {s.className}</span>{s.signals.map(signal => <small key={signal}>{signal}</small>)}</li>)}</ul> : <p className="analytics-empty">Şu anda bu kurallara uyan öğrenci yok. Bu sonuç tüm öğrencilerin yeterli çalıştığı anlamına gelmez.</p>}</section></>}
    {(!student && (view === 'home' || view === 'analytics' || classSection === 'overview')) && <section><div className="analytics-section-heading"><h2>Öğrenci karşılaştırması</h2><span>Oranı soru hacmiyle birlikte değerlendir.</span></div><div className="analytics-filters">{!classId && <label>Sınıf filtresi<select aria-label="Sınıf filtresi" value={filter} onChange={e => setFilter(e.target.value)}><option value="">Tüm sınıflar</option>{report.classes.map(c => <option key={c.classId} value={c.classId}>{c.className}</option>)}</select></label>}<label>Sıralama<select aria-label="Sıralama" value={sort} onChange={e => setSort(e.target.value)}>{[['most','En çok soru çözen'],['least','En az soru çözen'],['high','En yüksek başarı'],['low','En düşük başarı'],['xp','En yüksek XP'],['arena','Arena sırası']].map(([value,label]) => <option key={value} value={value}>{label}</option>)}</select></label></div><StudentTable students={visible} period={period}/></section>}
    {(cls || student) && (sectionTab === 'subjects' || sectionTab === 'topics' || !!student && sectionTab === 'general') && <section><h2>{sectionTab === 'topics' ? 'Konu performansı' : 'Ders performansı'}</h2><PerformanceRows dimensions={report.dimensions} period={period} kind={sectionTab === 'topics' ? 'topic' : 'subject'}/>{student && sectionTab === 'general' && <><h2>Konu performansı</h2><PerformanceRows dimensions={report.dimensions} period={period} kind="topic"/></>}</section>}
    <p className="analytics-footnote">İlk kabul edilen cevap sayılır; yeni testte tekrar çözme çalışmaya dahildir. Aynı soru yeniden XP üretmez. Kaldırılan öğrenciler aktif rapora dahil edilmez. Son yenileme: {new Date(report.serverNow).toLocaleTimeString('tr-TR')}.</p>
  </section>;
}
