import {test,expect} from '@playwright/test';
test('duel lobby, invitation, locked answer and result fit phone and desktop',async({page},info)=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
 await page.route('**/src/app/Session.tsx*',r=>r.fulfill({contentType:'application/javascript',body:`export const useSession=()=>({role:'student',loading:false,user:{uid:'a'},student:{studentId:'a',teacherUid:'t',classId:'c',className:'DOSTLAR',gradeLevel:6,firstName:'Ada'}});export const SessionProvider=({children})=>children;`}));
 await page.route('**/src/app/useArena.ts*',r=>r.fulfill({contentType:'application/javascript',body:`export const useArena=()=>({rows:[{studentId:'a',displayName:'Ada',academicXP:52},{studentId:'b',displayName:'Ali Yılmaz',academicXP:41}]});`}));
 await page.route('**/src/app/DuelLobby.tsx*',r=>r.fulfill({contentType:'application/javascript',body:`import React from '/node_modules/.vite/deps/react.js';let next;let state={now:100000,error:'',presence:[{studentId:'b',at:{toMillis:()=>100000}}],duels:[]};window.duelState=(s)=>{state={...state,...s};next?.({...state});};export const useDuelLobby=()=>{const [s,set]=React.useState(state);next=set;return s;};export const DuelLobby=({children})=>children;`}));
 await page.route('**/src/data/duel.mjs*',r=>r.fulfill({contentType:'application/javascript',body:`let next;export const duelStart=d=>d.acceptedAt.toMillis()+10000,duelEnd=d=>duelStart(d)+200000;export const duelRoundSeconds=()=>20;export const endDuel=async()=>{};export const duelScore=(d,a,s)=>a.filter(v=>v.studentId===s).length*1200;export const watchAnswers=(db,p,id,n)=>{next=n;n([]);return()=>{};};export const publishAnswer=async()=>next([{studentId:'a',index:0,isCorrect:true}]);export const heartbeat=async()=>{};export const watchLobby=()=>()=>{};export const invite=async()=>window.duelState({duels:[{id:'demo',from:'a',to:'b',participants:['a','b'],templateId:'pack',status:'pending',createdAt:{toMillis:()=>100000},acceptedAt:null}]});export const respond=async()=>{};`}));
 const questions=Array.from({length:10},(_,i)=>({questionId:'q'+i,questionText:`${i+1}. soru: Aşağıdaki kesirlerden hangisi daha büyüktür?`,choices:[{choiceId:'a',text:'3/4'},{choiceId:'b',text:'1/4'},{choiceId:'c',text:'1/2'}]}));
 await page.route('**/src/data/firebase.ts*',r=>r.fulfill({contentType:'application/javascript',body:`export const db={},auth={},app={},persistenceReady=Promise.resolve();let q={testSessionId:'demo-a',questions:${JSON.stringify(questions)},answeredQuestionIds:[],status:'active',correctCount:0,wrongCount:0,earnedXP:0,blankCount:0};export const call=async(n,d)=>{if(n==='quizCatalog')return {curricula:[{grade:6,subjects:[{name:'Matematik',units:[{displayName:'Kesirler',topics:[{packs:[{templateId:'pack',name:'Test 1',count:10}]}]}]}]}]};if(n==='submitAnswer'){q={...q,answeredQuestionIds:[...q.answeredQuestionIds,d.questionId],correctCount:d.selectedChoiceId?q.correctCount+1:q.correctCount};return {test:q};}if(n==='finishTest')q={...q,status:'completed',earnedXP:1};return q;};`}));
 await page.goto('/ogrenci/duello');await expect(page.getByRole('heading',{name:'Düello',exact:true})).toBeVisible();await expect(page.getByText('Ali Yılmaz',{exact:true})).toBeVisible();
 await page.screenshot({path:info.outputPath('duel-lobby.png'),fullPage:true});
 await page.getByRole('button',{name:'Davet et'}).click();await expect(page.getByText(/yanıtı bekleniyor/)).toBeVisible();
 await page.evaluate(()=>{(window as any).duelState({duels:[{id:'demo',from:'a',to:'b',participants:['a','b'],templateId:'pack',status:'active',createdAt:{toMillis:()=>90000},acceptedAt:{toMillis:()=>95000}}]});});
 await expect(page.getByText('Rakibin hazır!')).toBeVisible();await page.evaluate(()=>(window as any).duelState({now:106000}));
 await expect(page.getByText('Soru 1 / 10')).toBeVisible();await page.getByRole('button',{name:'A 3/4'}).click();await page.getByRole('button',{name:'Cevabı gönder'}).click();await expect(page.getByText('Cevabın kilitlendi.',{exact:false})).toBeVisible();
 await expect(page.getByRole('button',{name:'Yarışmadan ayrıl',exact:true})).toHaveCSS('color','rgb(24, 45, 73)');await page.screenshot({path:info.outputPath('duel-match.png'),fullPage:true});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await page.evaluate(()=>(window as any).duelState({now:306000}));await expect(page.getByRole('heading',{name:'Kazandın!'})).toBeVisible();await expect(page.getByText('+1 XP',{exact:true})).toBeVisible();await page.screenshot({path:info.outputPath('duel-result.png'),fullPage:true});expect(errors).toEqual([]);
});
