import { test, before, beforeEach, after } from 'node:test';
import assert from 'node:assert/strict';
import { collection, doc, getDoc, getDocs, setDoc } from 'firebase/firestore';
import { getApps, deleteApp } from 'firebase-admin/app';
import { getFirestore, Timestamp } from 'firebase-admin/firestore';
import { teacherClient, client, loginStudent, clearLimiter } from './helpers.mjs';
import { seedDemo } from '../scripts/seed-demo.mjs';
import { demoQuestions } from '../scripts/demo-questions.mjs';
import { arenaPeriod } from '../functions/lib/arena-store.js';
import { accuracy, currentSummary, emptySummary, acceptAnswer, supportSignals, dimensionIds } from '../functions/lib/analytics-store.js';
import { sortStudents, percent } from '../src/domain/analytics.ts';
import { rankArena } from '../src/domain/arena.ts';

let teacher, other, admin; const clients = [], keys = new Map(demoQuestions.map(q => [q.question.questionId, q.answer.correctChoiceId]));
const params = { gradeLevel: 6, subject: 'matematik', topic: 'kesirler', questionCount: 10 };
before(async () => { await seedDemo(); admin = getFirestore(getApps().find(a => a.name === 'demo-seed')); teacher = await teacherClient(); other = await teacherClient(); clients.push(teacher,other); });
beforeEach(clearLimiter);
after(async () => { await Promise.all(clients.map(c => c.close())); await Promise.all(getApps().map(deleteApp)); });
async function pupil(owner = teacher, classId) {
  classId ||= (await owner.call('createClass', { className: 'ANALYTICS', defaultGradeLevel: 6 })).classId;
  const record = await owner.call('createStudent', { classId, firstName: 'Deniz', lastName: 'Analiz', gradeLevel: 6 });
  const c = client(); clients.push(c); await loginStudent(c, record.code);
  return { ...record, c, owner, classId, path: ['teachers', owner.auth.currentUser.uid, 'students', record.studentId] };
}
const start = p => p.c.call('startTest', params);
const answer = (p,t,q,correct = true) => p.c.call('submitAnswer', { testSessionId: t.testSessionId, questionId: q.questionId,
  selectedChoiceId: correct ? keys.get(q.questionId) : q.choices.find(c => c.choiceId !== keys.get(q.questionId)).choiceId });
const report = p => p.owner.call('teacherAnalytics', { studentId: p.studentId });
const own = (p,r) => r.students.find(s => s.studentId === p.studentId);
const stored = async p => (await getDoc(doc(p.owner.db, ...p.path, 'analytics', 'summary'))).data();
async function fill(p, correct = true, options = params) { const t = await p.c.call('startTest', options); for (const q of t.questions) await answer(p,t,q,correct); return t; }

test('Teacher A reads own class analytics and summary', async () => { const p = await pupil(); assert.equal((await teacher.call('teacherAnalytics', { classId: p.classId })).classes.find(c => c.classId === p.classId).studentCount, 1); assert.equal((await stored(p)).overall.solved,0); });
test('Teacher A cannot read Teacher B summaries, topic detail or class callable', async () => { const p = await pupil(other); await assert.rejects(teacher.call('teacherAnalytics', { classId: p.classId })); await assert.rejects(teacher.call('teacherAnalytics', { studentId: p.studentId })); for (const suffix of [['analytics','summary'],['analyticsDimensions','subject:6:matematik']]) await assert.rejects(getDoc(doc(teacher.db,...p.path,...suffix))); });
test('student and anonymous callers cannot read teacher analytics', async () => { const p = await pupil(), anon = client(); clients.push(anon); for (const c of [p.c,anon]) { await assert.rejects(c.call('teacherAnalytics', {})); for (const suffix of [['analytics','summary'],['analyticsDimensions','subject:6:matematik']]) await assert.rejects(getDoc(doc(c.db,...p.path,...suffix))); } });
test('all clients are denied analytics writes; forged teacherUid rejected', async () => { const p = await pupil(); for (const c of [teacher,other,p.c]) for (const suffix of [['analytics','summary'],['analyticsDimensions','x']]) await assert.rejects(setDoc(doc(c.db,...p.path,...suffix), { overall: {solved:999} })); await assert.rejects(teacher.call('teacherAnalytics',{teacherUid:other.auth.currentUser.uid})); });
test('correct answer increments solved and correct exactly once', async () => { const p = await pupil(), t = await start(p); await answer(p,t,t.questions[0]); assert.deepEqual((await stored(p)).overall, { solved:1,correct:1,wrong:0 }); });
test('wrong answer increments solved and wrong with zero XP', async () => { const p = await pupil(), t = await start(p); const a = await answer(p,t,t.questions[0],false); assert.equal(a.answer.earnedXP,0); assert.deepEqual((await stored(p)).overall,{solved:1,correct:0,wrong:1}); });
test('accuracy is weighted correct/accepted answers, not mean student rates', async () => { const p = await pupil(), q = await pupil(teacher,p.classId), t = await start(p), u = await start(q); await answer(p,t,t.questions[0],true); for (let i=0;i<3;i++) await answer(q,u,u.questions[i],i===0); const r = await teacher.call('teacherAnalytics',{classId:p.classId}), c = r.classes.find(c=>c.classId===p.classId); assert.equal(accuracy(c.overall),50); assert.equal(c.overall.solved,4); });
test('solved count and XP stay independent when practice includes wrong answers', async () => { const p = await pupil(), t = await start(p); await answer(p,t,t.questions[0]); await answer(p,t,t.questions[1],false); const s = own(p,await report(p)); assert.equal(s.overall.solved,2); assert.equal(s.academicXP,1); });
test('previously awarded question in new attempt earns no new XP but adds practice', async () => { const p = await pupil(), a = await start(p), b = await start(p), q = a.questions.find(q => b.questions.some(x=>x.questionId===q.questionId)); await answer(p,a,q); const second = await answer(p,b,q); assert.equal(second.answer.earnedXP,0); const s=own(p,await report(p)); assert.equal(s.overall.solved,2); assert.equal(s.academicXP,1); });
test('same request retry never increments solved twice', async () => { const p=await pupil(),t=await start(p),q=t.questions[0]; await answer(p,t,q); await answer(p,t,q); assert.equal((await stored(p)).overall.solved,1); });
test('changed choice for the same test question keeps first answer and analytics', async () => { const p=await pupil(),t=await start(p),q=t.questions[0]; await answer(p,t,q,false); const replay=await answer(p,t,q,true); assert.equal(replay.answer.isCorrect,false); assert.deepEqual((await stored(p)).overall,{solved:1,correct:0,wrong:1}); });
test('concurrent identical submissions count once', async () => { const p=await pupil(),t=await start(p),q=t.questions[0]; await Promise.all(Array.from({length:5},()=>answer(p,t,q))); assert.equal((await stored(p)).overall.solved,1); });
test('concurrent different attempts count twice and award once', async () => { const p=await pupil(),a=await start(p),b=await start(p),q=a.questions.find(q=>b.questions.some(x=>x.questionId===q.questionId)); const results=await Promise.all([answer(p,a,q),answer(p,b,q)]); assert.equal(results.reduce((n,r)=>n+r.answer.earnedXP,0),1); assert.equal((await stored(p)).overall.solved,2); });
test('subject summary matches accepted answers and is separate by content grade', async () => { const p=await pupil(),t=await start(p); await answer(p,t,t.questions[0]); await answer(p,t,t.questions[1],false); const previous=await p.c.call('startTest',{...params,gradeLevel:5}); await answer(p,previous,previous.questions[0]); const r=await report(p), subjects=r.dimensions.filter(d=>d.kind==='subject'); assert.equal(subjects.length,2); assert.equal(subjects.find(d=>d.gradeLevel===6).overall.solved,2); assert.equal(subjects.find(d=>d.gradeLevel===5).overall.solved,1); });
test('topic summary carries honest subject/name, correct and wrong counts', async () => { const p=await pupil(),t=await start(p); await answer(p,t,t.questions[0]); await answer(p,t,t.questions[1],false); const topic=(await report(p)).dimensions.find(d=>d.kind==='topic'); assert.equal(topic.topicName,'Kesirler'); assert.equal(topic.subjectName,'Matematik'); assert.deepEqual(topic.overall,{solved:2,correct:1,wrong:1}); });
test('class summary equals active student summaries and dimensions', async () => { const p=await pupil(),q=await pupil(teacher,p.classId); await fill(p); const t=await start(q); await answer(q,t,t.questions[0],false); const r=await teacher.call('teacherAnalytics',{classId:p.classId}),c=r.classes.find(c=>c.classId===p.classId); assert.deepEqual(c.overall,{solved:11,correct:10,wrong:1}); assert.equal(r.dimensions.find(d=>d.kind==='topic').overall.solved,11); });
test('weekly summary reuses Istanbul week boundary and masks previous week', () => { const before=new Date('2026-10-04T20:59:59.999Z'),after=new Date('2026-10-04T21:00:00Z'),base={...emptySummary(before),overall:{solved:100,correct:76,wrong:24},weekly:{solved:10,correct:7,wrong:3}}; assert.equal(base.weekKey,arenaPeriod(before).weekKey); assert.equal(currentSummary(base,after).weekKey,'2026-W41'); assert.deepEqual(currentSummary(base,after).weekly,{solved:0,correct:0,wrong:0}); });
test('general counts and dimension names survive rollover; no-data is null', () => { const now=new Date(),base={...emptySummary(new Date('2020-01-01')),overall:{solved:100,correct:76,wrong:24}}; assert.equal(currentSummary(base,now).overall.solved,100); assert.equal(accuracy(base.overall),76); assert.equal(accuracy(emptySummary().overall),null); assert.equal(percent(emptySummary().overall),'Henüz veri yok'); });
test('unanswered student has no false zero-success or support signal', async () => { const p=await pupil(),s=own(p,await report(p)); assert.equal(accuracy(s.overall),null); assert.deepEqual(s.signals,[]); });
test('moving student transfers lifetime analytics to current class, without copying history', async () => { const p=await pupil(); await fill(p); const target=await teacher.call('createClass',{className:'YENİ',defaultGradeLevel:6}); await teacher.call('updateStudent',{studentId:p.studentId,classId:target.classId,gradeLevel:6}); const r=await teacher.call('teacherAnalytics',{}); assert.equal(r.classes.find(c=>c.classId===p.classId).overall.solved,0); assert.equal(r.classes.find(c=>c.classId===target.classId).overall.solved,10); assert.equal(own(p,r).classId,target.classId); });
test('removal archives canonical/derived history but excludes active teacher reports', async () => { const p=await pupil(); await fill(p); await teacher.call('removeStudent',{studentId:p.studentId}); const r=await teacher.call('teacherAnalytics',{classId:p.classId}); assert.equal(r.classes.find(c=>c.classId===p.classId).overall.solved,0); assert.ok(!r.students.some(s=>s.studentId===p.studentId)); assert.equal((await stored(p)).overall.solved,10); await assert.rejects(teacher.call('teacherAnalytics',{studentId:p.studentId})); });
test('filters and all six sort modes use period metrics; no-data sorts after rates', () => { const make=(id,solved,correct,xp,rank)=>({studentId:id,displayName:id,classId:id==='C'?'other':'group',overall:{solved,correct,wrong:solved-correct},weekly:{solved:solved/2,correct:correct/2,wrong:(solved-correct)/2},academicXP:xp,weeklyAcademicXP:xp/2,overallRank:rank,weeklyRank:rank}); const rows=[make('A',100,75,70,2),make('B',10,10,9,3),make('C',0,0,100,1)]; assert.deepEqual(sortStudents(rows,'most','overall').map(s=>s.studentId),['A','B','C']); assert.equal(sortStudents(rows,'least','overall')[0].studentId,'C'); assert.equal(sortStudents(rows,'high','overall')[0].studentId,'B'); assert.equal(sortStudents(rows,'low','overall')[0].studentId,'A'); for(const mode of ['xp','arena']) assert.equal(sortStudents(rows,mode,'weekly')[0].studentId,'C'); assert.equal(sortStudents(rows.filter(s=>s.classId==='group'),'most','weekly').length,2); });
test('one-time legacy rebuild uses canonical answers, excludes retries and includes old-started tests answered this week', async () => { const p=await pupil(),t=await fill(p); const root=admin.doc(p.path.join('/')); await root.collection('analytics').doc('summary').delete(); const dims=await root.collection('analyticsDimensions').get(); for(const d of dims.docs) await d.ref.delete(); await root.collection('testSessions').doc(t.testSessionId).update({startedAt:Timestamp.fromDate(new Date('2020-01-01'))}); const r=await report(p),s=own(p,r); assert.equal(s.overall.solved,10); assert.equal(s.weekly.solved,10); assert.equal(r.dimensions.find(d=>d.kind==='topic').overall.solved,10); assert.equal((await stored(p)).version,2); });
test('legacy rebuild and concurrent new answer are serialized without double count', async () => { const p=await pupil(),t=await start(p); await answer(p,t,t.questions[0]); const root=admin.doc(p.path.join('/')); await root.collection('analytics').doc('summary').delete(); const docs=await root.collection('analyticsDimensions').get(); for(const d of docs.docs) await d.ref.delete(); await Promise.all([report(p),answer(p,t,t.questions[1],false)]); assert.deepEqual((await stored(p)).overall,{solved:2,correct:1,wrong:1}); });
test('support threshold excludes tiny samples and explains low accuracy after 20 answers', async () => { const p=await pupil(); await fill(p,false); assert.deepEqual(own(p,await report(p)).signals,[]); await fill(p,false); assert.deepEqual(own(p,await report(p)).signals,['En az 20 cevapta başarı %60 altında.']); });
test('weekly dimension/general rebuild respects acceptance timestamp, not XP award date', async () => { const p=await pupil(),t=await fill(p); const root=admin.doc(p.path.join('/')),old=Timestamp.fromDate(new Date('2020-01-01')); const answers=await root.collection('testSessions').doc(t.testSessionId).collection('answers').get(); for(const a of answers.docs) await a.ref.update({answeredAt:old}); await root.collection('analytics').doc('summary').delete(); const dims=await root.collection('analyticsDimensions').get(); for(const d of dims.docs) await d.ref.delete(); const r=await report(p); assert.equal(own(p,r).overall.solved,10); assert.equal(own(p,r).weekly.solved,0); assert.equal(r.dimensions.find(d=>d.kind==='topic').weekly.solved,0); });
test('two different subjects remain independent and sum to student totals', async () => { const p=await pupil(); await fill(p,true); await fill(p,false,{...params,subject:'ingilizce',topic:'temel-kelimeler'}); const r=await report(p),subjects=r.dimensions.filter(d=>d.kind==='subject'); assert.equal(subjects.length,2); assert.equal(subjects.find(s=>s.subject==='matematik').overall.correct,10); assert.equal(subjects.find(s=>s.subject==='ingilizce').overall.wrong,10); assert.equal(own(p,r).overall.solved,20); });
test('accepted timestamp, weekly summary and dimension use the same Istanbul period', async () => { const p=await pupil(),t=await start(p),q=t.questions[0];await answer(p,t,q);const storedAnswer=(await getDoc(doc(teacher.db,...p.path,'testSessions',t.testSessionId,'answers',q.questionId))).data(),s=await stored(p);assert.equal(s.weekKey,arenaPeriod(storedAnswer.answeredAt.toDate()).weekKey);assert.deepEqual(s.weekly,{solved:1,correct:1,wrong:0});assert.equal((await report(p)).dimensions.find(d=>d.kind==='topic').weekly.solved,1); });
test('first answer in a new week resets weekly only for summary, subject and topic', () => { const before=new Date('2026-10-04T20:59:59.999Z'),after=new Date('2026-10-04T21:00:00Z'); const base={...emptySummary(before),overall:{solved:100,correct:76,wrong:24},weekly:{solved:10,correct:7,wrong:3}};const plan={summary:base,dimensions:new Map([['subject:6:matematik',{...base,kind:'subject'}],['topic:6:matematik:kesirler',{...base,kind:'topic'}]])}; acceptAnswer(plan,{gradeLevel:6,subject:'matematik',topic:'kesirler'},false,after);for(const item of [plan.summary,...plan.dimensions.values()]) {assert.deepEqual(item.overall,{solved:101,correct:76,wrong:25});assert.deepEqual(item.weekly,{solved:1,correct:0,wrong:1});assert.equal(item.weekKey,'2026-W41');} });
test('relative weekly support needs three peers, median ten, three days and enrollment age', () => {const now=new Date('2026-10-08T22:00:00Z'),s={overall:{solved:1,correct:1,wrong:0},weekly:{solved:1,correct:1,wrong:0},createdAt:Date.parse('2026-09-01'),lastAnswerAt:now.getTime()};assert.equal(supportSignals(s,[1,10,20],now).length,1);assert.deepEqual(supportSignals(s,[1,9,20],now),[]);assert.deepEqual(supportSignals(s,[1,20],now),[]);assert.deepEqual(supportSignals({...s,createdAt:now.getTime()},[1,10,20],now),[]);assert.deepEqual(supportSignals(s,[1,10,20],new Date('2026-10-05T22:00:00Z')),[]);});
test('inactive support needs at least twenty answers and seven days',()=>{const now=new Date('2026-10-08'),s={overall:{solved:20,correct:20,wrong:0},weekly:{solved:0,correct:0,wrong:0},createdAt:0,lastAnswerAt:now.getTime()-7*86400000};assert.deepEqual(supportSignals(s,[0],now),['Son kabul edilen cevap en az 7 gün önce.']);assert.deepEqual(supportSignals({...s,overall:{solved:2,correct:1,wrong:1}},[0],now),[]);});
test('teacher general/weekly ranks match the existing public Arena projection including ties',async()=>{const p=await pupil(),q=await pupil(teacher,p.classId),empty=await pupil(teacher,p.classId);for(const student of [p,q]){const t=await start(student);await answer(student,t,t.questions[0]);}const r=await teacher.call('teacherAnalytics',{classId:p.classId}),rows=(await getDocs(collection(teacher.db,'teachers',teacher.auth.currentUser.uid,'classes',p.classId,'leaderboard'))).docs.map(d=>d.data());for(const mode of ['overall','weekly'])for(const ranked of rankArena(rows,mode,r.weekKey)){const s=r.students.find(s=>s.studentId===ranked.studentId);assert.equal(s[mode==='overall'?'overallRank':'weeklyRank'],ranked.rank);}assert.equal(own(empty,r).overallRank,3);});
test('normal report reads summaries without rescanning canonical answers or rewriting XP',async()=>{const p=await pupil(),t=await fill(p),root=admin.doc(p.path.join('/')),xp=(await getDoc(doc(teacher.db,...p.path,'learning','summary'))).data();await root.collection('testSessions').doc(t.testSessionId).collection('answers').doc(t.questions[0].questionId).update({answeredAt:null});const r=await report(p);assert.equal(own(p,r).overall.solved,10);assert.deepEqual((await getDoc(doc(teacher.db,...p.path,'learning','summary'))).data(),xp);await root.collection('testSessions').doc(t.testSessionId).collection('answers').doc(t.questions[0].questionId).update({answeredAt:Timestamp.now()});});

test('dimension identifiers do not collide when subject/topic contain underscores',()=>{assert.notEqual(dimensionIds({gradeLevel:6,subject:'a_b',topic:'c'})[1],dimensionIds({gradeLevel:6,subject:'a',topic:'b_c'})[1]);});
test('earlier analytics key version rebuilds canonically and removes obsolete derived documents',async()=>{const p=await pupil(),t=await fill(p),root=admin.doc(p.path.join('/'));await root.collection('analytics').doc('summary').update({version:1});await root.collection('analyticsDimensions').doc('old_ambiguous_key').set({...emptySummary(),version:1,kind:'topic',overall:{solved:999,correct:999,wrong:0}});const r=await report(p);assert.equal(own(p,r).overall.solved,10);assert.equal(r.dimensions.length,2);assert.equal((await root.collection('analyticsDimensions').doc('old_ambiguous_key').get()).exists,false);assert.equal((await stored(p)).version,2);});
