import { test, before, beforeEach, after } from 'node:test';
import assert from 'node:assert/strict';
import { doc, getDoc, getDocs, collection, setDoc } from 'firebase/firestore';
import { getApps, deleteApp } from 'firebase-admin/app';
import { getFirestore, Timestamp, FieldValue } from 'firebase-admin/firestore';
import { teacherClient, client, loginStudent, clearLimiter } from './helpers.mjs';
import { seedDemo } from '../scripts/seed-demo.mjs';
import { demoQuestions } from '../scripts/demo-questions.mjs';
import { arenaPeriod } from '../functions/lib/arena-store.js';
import { rankArena, arenaPosition } from '../src/domain/arena.ts';

const keys = new Map(demoQuestions.map(e => [e.question.questionId, e.answer.correctChoiceId]));
const clients = []; let teacher, other, cls, admin;
const params = { gradeLevel: 6, subject: 'matematik', topic: 'kesirler', questionCount: 10 };
before(async () => { await seedDemo(); admin = getFirestore(getApps().find(a => a.name === 'demo-seed')); teacher = await teacherClient(); other = await teacherClient(); clients.push(teacher, other); cls = await teacher.call('createClass', { className: 'DOSTLAR', defaultGradeLevel: 6 }); });
beforeEach(clearLimiter);
after(async () => { await Promise.all(clients.map(c => c.close())); await Promise.all(getApps().map(deleteApp)); });
async function pupil(classId = cls.classId, firstName = 'Deniz') { const record = await teacher.call('createStudent', { classId, firstName, lastName: 'Arena', gradeLevel: 6 }); const c = client(); clients.push(c); await loginStudent(c, record.code); return { c, ...record, classId, path: ['teachers', teacher.auth.currentUser.uid, 'students', record.studentId] }; }
const rowPath = p => ['teachers', teacher.auth.currentUser.uid, 'classes', p.classId, 'leaderboard', p.studentId];
const row = async p => (await getDoc(doc(p.c.db, ...rowPath(p)))).data();
const start = p => p.c.call('startTest', params);
const answer = (p, t, q, choice = keys.get(q.questionId)) => p.c.call('submitAnswer', { testSessionId: t.testSessionId, questionId: q.questionId, selectedChoiceId: choice });
const academic = async p => (await getDoc(doc(p.c.db, ...p.path, 'learning', 'summary'))).data();
const fixtures = scores => scores.map((score, i) => ({ studentId: String(i), classId: 'group', displayName: ['Ece','Mehmet','Ahmet','Kerem'][i] || 'Test', academicXP: score, weeklyAcademicXP: score, weekKey: '2026-W41' }));

test('Istanbul week starts Monday at local midnight and is half-open', () => {
  const before = arenaPeriod(new Date('2026-10-04T20:59:59.999Z')), after = arenaPeriod(new Date('2026-10-04T21:00:00.000Z'));
  assert.equal(before.weekKey, '2026-W40'); assert.equal(after.weekKey, '2026-W41'); assert.equal(before.endsAt, after.startsAt);
  assert.equal(after.startsAt, Date.parse('2026-10-04T21:00:00Z')); assert.equal(after.endsAt, Date.parse('2026-10-11T21:00:00Z'));
});
test('ISO week-year rollover handles week 53 and year boundary', () => { assert.equal(arenaPeriod(new Date('2021-01-01T10:00:00Z')).weekKey, '2020-W53'); assert.equal(arenaPeriod(new Date('2021-01-04T00:00:00Z')).weekKey, '2021-W01'); });
test('competition ranking shares ties and skips ranks 1,1,3,4', () => { const rows = rankArena(fixtures([120,120,115,0]), 'overall', '2026-W41'); assert.deepEqual(rows.map(r => r.rank), [1,1,3,4]); });
test('stable secondary order never creates different ranks within a tie', () => { const rows = fixtures([4,4,4]); assert.deepEqual(rankArena(rows.reverse(), 'weekly', '2026-W41').map(r => [r.studentId,r.rank]), [['0',1],['1',1],['2',1]]); });
test('passing closest strictly higher rival requires difference plus one', () => { const pos = arenaPosition(rankArena(fixtures([1820,1770,1725,1680]), 'overall', ''), '2'); assert.equal(pos.target.displayName, 'Mehmet'); assert.equal(pos.neededXP, 46); });
test('tied higher group is one target rank; ties at own score are not targets', () => { const pos = arenaPosition(rankArena(fixtures([120,120,115,115]), 'overall', ''), '3'); assert.equal(pos.target.rank, 1); assert.equal(pos.targetTieCount, 2); assert.equal(pos.neededXP, 6); });
test('leaders including tied leaders return summit state', () => { const pos = arenaPosition(rankArena(fixtures([7,7,2]), 'overall', ''), '1'); assert.equal(pos.own.rank, 1); assert.equal(pos.target, null); assert.equal(pos.neededXP, 0); });
test('new week masks previous bucket scores but preserves overall academic XP', () => { const data = fixtures([120,110]); assert.deepEqual(rankArena(data, 'weekly', '2026-W42').map(r => r.score), [0,0]); assert.deepEqual(rankArena(data, 'overall', '2026-W42').map(r => r.score), [120,110]); });

test('own class leaderboard is readable with only minimum public fields', async () => { const p = await pupil(); await p.c.call('prepareArena', {}); const data = await row(p); assert.deepEqual(Object.keys(data).sort(), ['academicXP','classId','displayName','studentId','weekKey','weeklyAcademicXP'].sort()); assert.equal(data.academicXP, 0); assert.ok((await getDocs(collection(p.c.db, ...rowPath(p).slice(0,-1)))).size >= 1); });
test('student cannot read another group of same teacher', async () => { const p = await pupil(), target = await teacher.call('createClass', { className: 'BAŞKA', defaultGradeLevel: 6 }); const q = await pupil(target.classId); await assert.rejects(getDoc(doc(p.c.db, ...rowPath(q)))); await assert.rejects(getDocs(collection(p.c.db, ...rowPath(q).slice(0,-1)))); });
test('student and foreign teacher cannot read another teacher Arena', async () => { const p = await pupil(); const otherClass = await other.call('createClass', { className: 'GİZLİ', defaultGradeLevel: 6 }); await assert.rejects(getDocs(collection(p.c.db, 'teachers', other.auth.currentUser.uid, 'classes', otherClass.classId, 'leaderboard'))); await assert.rejects(getDoc(doc(other.db, ...rowPath(p)))); assert.equal((await getDoc(doc(teacher.db, ...rowPath(p)))).exists(), true); });
test('anonymous and teacher caller cannot use student Arena API; forged XP or class rejected', async () => { const p = await pupil(), anonymous = client(); clients.push(anonymous); for (const c of [teacher, anonymous]) await assert.rejects(c.call('prepareArena', {})); for (const extra of [{ classId: cls.classId }, { teacherUid: teacher.auth.currentUser.uid }, { academicXP: 999 }, { rank: 1 }, { now: '2026-01-01' }]) await assert.rejects(p.c.call('prepareArena', extra)); });
test('all clients including owner teacher cannot write leaderboard or weekly buckets', async () => { const p = await pupil(); for (const c of [p.c, teacher, other]) { await assert.rejects(setDoc(doc(c.db, ...rowPath(p)), { academicXP: 999 })); await assert.rejects(setDoc(doc(c.db, ...p.path, 'academicWeeks', '2026-W41'), { academicXP: 999 })); } });
test('classmates cannot read private codes, sessions, tests, performance or weekly buckets', async () => { const p = await pupil(), q = await pupil(); for (const tail of [['learning','summary'],['academicWeeks',arenaPeriod().weekKey],['testSessions','x'],['performance','x']]) await assert.rejects(getDoc(doc(p.c.db, ...q.path, ...tail))); await assert.rejects(getDoc(doc(p.c.db,'studentSessions',q.c.auth.currentUser.uid))); await assert.rejects(getDoc(doc(p.c.db,'teachers',teacher.auth.currentUser.uid,'studentCodes',q.studentId))); });
test('first correct atomically awards academic total, weekly bucket and read model', async () => { const p = await pupil(), t = await start(p); await answer(p,t,t.questions[0]); const data = await row(p), summary = await academic(p), bucket = (await getDoc(doc(p.c.db,...p.path,'academicWeeks',data.weekKey))).data(); assert.equal(summary.totalXP,1); assert.equal(summary.academicXP,1); assert.equal(bucket.academicXP,1); assert.equal(data.academicXP,1); assert.equal(data.weeklyAcademicXP,1); });
test('wrong answer leaves both leaderboard XP values unchanged', async () => { const p = await pupil(), t = await start(p), q = t.questions[0]; await answer(p,t,q,q.choices.find(c => c.choiceId !== keys.get(q.questionId)).choiceId); assert.equal((await row(p)).academicXP,0); assert.equal((await row(p)).weeklyAcademicXP,0); });
test('concurrent retries produce only one total, weekly and Arena XP', async () => { const p = await pupil(), t = await start(p); await Promise.all(Array.from({length:4},()=>answer(p,t,t.questions[0]))); const data = await row(p); assert.equal(data.academicXP,1); assert.equal(data.weeklyAcademicXP,1); assert.equal((await academic(p)).totalXP,1); });
test('same awarded question in another test cannot increase Arena XP', async () => { const p = await pupil(), a = await start(p), b = await start(p), q = a.questions.find(q=>b.questions.some(x=>x.questionId===q.questionId)); await answer(p,a,q); await answer(p,b,q); assert.equal((await row(p)).academicXP,1); assert.equal((await row(p)).weeklyAcademicXP,1); });
test('class move atomically removes old row, preserves identity, totals, bucket and new row', async () => { const p = await pupil(), t = await start(p); await answer(p,t,t.questions[0]); const target = await teacher.call('createClass',{className:'YENİ',defaultGradeLevel:7}); await teacher.call('updateStudent',{studentId:p.studentId,classId:target.classId,gradeLevel:6}); assert.equal((await getDoc(doc(teacher.db,...rowPath(p)))).exists(),false); await assert.rejects(getDocs(collection(p.c.db,...rowPath(p).slice(0,-1)))); p.classId=target.classId; const data=await row(p); assert.equal(data.studentId,p.studentId); assert.equal(data.academicXP,1); assert.equal(data.weeklyAcademicXP,1); assert.equal((await academic(p)).totalXP,1); assert.equal((await p.c.call('prepareArena',{})).classId,target.classId); await answer(p,t,t.questions[1]); assert.equal((await row(p)).academicXP,2); });
test('move concurrent with correct answer cannot recreate old class row or lose XP', async () => { const p=await pupil(),t=await start(p),target=await teacher.call('createClass',{className:'TAŞIMA',defaultGradeLevel:6}); await Promise.all([answer(p,t,t.questions[0]),teacher.call('updateStudent',{studentId:p.studentId,classId:target.classId,gradeLevel:6})]); assert.equal((await getDoc(doc(teacher.db,...rowPath(p)))).exists(),false); p.classId=target.classId; assert.equal((await row(p)).academicXP,1); assert.equal((await row(p)).weeklyAcademicXP,1); });
test('removal deletes Arena row, revokes API and recalculates peers rank', async () => { const target=await teacher.call('createClass',{className:'KALDIR',defaultGradeLevel:6}), a=await pupil(target.classId),b=await pupil(target.classId); const t=await start(a);await answer(a,t,t.questions[0]); const list=async()=> (await getDocs(collection(b.c.db,...rowPath(b).slice(0,-1)))).docs.map(d=>d.data()); assert.equal(arenaPosition(rankArena(await list(),'overall',''),b.studentId).own.rank,2); await teacher.call('removeStudent',{studentId:a.studentId}); await assert.rejects(a.c.call('prepareArena',{})); await assert.rejects(getDocs(collection(a.c.db,...rowPath(a).slice(0,-1)))); assert.equal((await list()).length,1);assert.equal(arenaPosition(rankArena(await list(),'overall',''),b.studentId).own.rank,1); });
test('rotation revokes old Arena token; fresh token keeps academic XP', async () => { const p=await pupil(),t=await start(p);await answer(p,t,t.questions[0]);const next=await teacher.call('rotateStudentCode',{studentId:p.studentId});await assert.rejects(p.c.call('prepareArena',{}));await assert.rejects(getDoc(doc(p.c.db,...rowPath(p))));await loginStudent(p.c,next.code);await p.c.call('prepareArena',{});assert.equal((await row(p)).academicXP,1); });
test('new week award preserves old bucket and lifetime totals', async () => { const p=await pupil(), current=arenaPeriod(), old=arenaPeriod(new Date(current.startsAt-1)); const root=admin.doc(p.path.join('/')); await root.collection('learning').doc('summary').set({totalXP:2,academicXP:2,answeredCount:2,correctCount:2,wrongCount:0}); await root.collection('academicWeeks').doc(old.weekKey).set({weekKey:old.weekKey,academicXP:2}); await admin.doc(rowPath(p).join('/')).update({academicXP:2,weeklyAcademicXP:2,weekKey:old.weekKey}); assert.equal(rankArena([await row(p)],'weekly',current.weekKey)[0].score,0); const t=await start(p); await answer(p,t,t.questions[0]); const data=await row(p);assert.equal(data.weekKey,current.weekKey);assert.equal(data.weeklyAcademicXP,1);assert.equal(data.academicXP,3);assert.equal((await academic(p)).totalXP,3);assert.equal((await root.collection('academicWeeks').doc(old.weekKey).get()).data().academicXP,2); });
test('legacy M2 totals and current-week awards backfill once without duplicate XP', async () => { const target=await teacher.call('createClass',{className:'ESKİ M2',defaultGradeLevel:6}),p=await pupil(target.classId),root=admin.doc(p.path.join('/')),period=arenaPeriod(); await admin.doc(`teachers/${teacher.auth.currentUser.uid}/classes/${target.classId}`).update({arenaVersion:FieldValue.delete()}); await root.collection('learning').doc('summary').set({totalXP:2,answeredCount:2,correctCount:2,wrongCount:0}); for(let i=0;i<2;i++)await root.collection('awardedQuestions').doc(`legacy${i}`).set({xp:1,awardedAt:Timestamp.fromMillis(period.startsAt+1000)}); await admin.doc(rowPath(p).join('/')).delete(); await Promise.all([p.c.call('prepareArena',{}),p.c.call('prepareArena',{})]); assert.equal((await row(p)).academicXP,2);assert.equal((await row(p)).weeklyAcademicXP,2);assert.equal((await academic(p)).totalXP,2);await p.c.call('prepareArena',{});assert.equal((await row(p)).weeklyAcademicXP,2); });

test('legacy first wrong answer does not discard previously earned weekly XP', async () => {
  const p = await pupil(), root = admin.doc(p.path.join('/')), period = arenaPeriod();
  await root.collection('learning').doc('summary').set({ totalXP: 1, answeredCount: 1, correctCount: 1, wrongCount: 0 });
  await root.collection('awardedQuestions').doc('legacy').set({ xp: 1, awardedAt: Timestamp.fromMillis(period.startsAt + 1000) });
  const t = await start(p), q = t.questions[0]; await answer(p, t, q, q.choices.find(c => c.choiceId !== keys.get(q.questionId)).choiceId);
  assert.equal((await row(p)).weeklyAcademicXP, 1); await answer(p, t, t.questions[1]);
  assert.equal((await row(p)).weeklyAcademicXP, 2); assert.equal((await academic(p)).totalXP, 2);
});
