import {test,before,after} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync,cpSync,mkdtempSync,writeFileSync,rmSync} from 'node:fs';
import {resolve,join,sep} from 'node:path';
import {parseVisual,parsePresentation,resolveStimulus,visualKinds} from '../functions/visuals/contract.mjs';
import {loadCurriculumBank} from '../scripts/curriculum-bank.mjs';
import {teacherClient,client,loginStudent,clearLimiter} from './helpers.mjs';
import {disposeFixture} from './classroom-fixture.mjs';
import {visualFixture} from './visual-fixture.mjs';
const source=JSON.parse(readFileSync('tests/fixtures/math-engine-questions.json','utf8'));
const present=q=>parsePresentation(q.question,q.options.map(o=>({choiceId:o.id,text:o.text,visual:o.visual})),resolveStimulus(q.visual,q.stimulusId,source.stimuli),q.visualPlacement);
function nodes(v){return !v?[]:v.kind==='scene'?[v,...v.items.flatMap(nodes)]:[v];}
let fixture,owner,foreign,pupilClient,student,classId;
before(async()=>{await clearLimiter();fixture=await visualFixture(source,30);owner=await teacherClient();foreign=await teacherClient();classId=(await owner.call('createClass',{className:'MATH ENGINE TEST',defaultGradeLevel:2})).classId;student=await owner.call('createStudent',{classId,firstName:'Model',lastName:'Test',gradeLevel:2});pupilClient=client();await loginStudent(pupilClient,student.code);});
after(async()=>{if(pupilClient)await pupilClient.close();for(const c of [owner,foreign])if(c)await disposeFixture(c);if(fixture)await fixture.close();});
test('all 30 original fixtures validate and exercise the original whitelist kinds',()=>{const kinds=new Set();for(const q of source.questions){const p=present(q);for(const v of nodes(p.visual).concat(p.choices.flatMap(c=>nodes(c.visual))))kinds.add(v.kind);}assert.deepEqual([...kinds].sort(),visualKinds.filter(k=>!['object','composition'].includes(k)&&!k.startsWith('school-')).sort());assert.equal(source.questions.length,30);assert.equal(new Set(source.questions.map(q=>q.id)).size,30);});
test('every nested node fails closed on arbitrary SVG HTML URL CSS component and correctness fields',()=>{for(const q of source.questions){const p=present(q);for(const v of nodes(p.visual).concat(p.choices.flatMap(c=>nodes(c.visual))))for(const key of ['svg','html','url','css','component','correctOptionId','answer','computedResult'])assert.throws(()=>parseVisual({...v,[key]:'unsafe'}));}for(const kind of ['constructor','toString','__proto__','image','unknown'])assert.throws(()=>parseVisual({kind,alt:'Görsel'}));});
test('bounded semantic parameters reject inconsistent capacity, balance, grouping, indices and oversized scenes',()=>{
 const bad=[{kind:'objects',objectType:'pencil',count:101,layout:'grid'},{kind:'base-ten',tens:2.5,ones:0},{kind:'clock',hour:24,minute:0},{kind:'clock',hour:2,minute:60},{kind:'groups',objectType:'apple',totalObjects:13,groupCount:3,arrangement:'plates'},{kind:'groups',objectType:'apple',totalObjects:12,groupCount:3,objectsPerGroup:4,arrangement:'plates'},{kind:'fraction',model:'circle',parts:[1,1],shaded:[0,0]},{kind:'fraction',model:'bar',parts:[1,1],shaded:[2]},{kind:'container',vessel:'glass',capacityClass:'small',fill:1,capacityMl:200,amountMl:100},{kind:'balance',left:{objectType:'apple',value:3,unit:'kg'},right:{objectType:'book',value:1,unit:'kg'},tilt:'right'},{kind:'geometry-layout',items:[{shape:'cylinder',row:0,column:0,size:'large',rotation:0,mark:'vertex'}]}];for(const v of bad)assert.throws(()=>parseVisual({...v,alt:'Verilen model'}));
 const leaf=present(source.questions[0]).visual;assert.throws(()=>parseVisual({kind:'scene',alt:'Sahne',preset:'stack',items:Array(6).fill(leaf)}));assert.throws(()=>parseVisual({kind:'scene',alt:'Sahne',preset:'stack',items:[{kind:'scene',alt:'Alt sahne',preset:'stack',items:[leaf]}]}));assert.throws(()=>parsePresentation('Soru',[{choiceId:'a',text:'A'},{choiceId:'b',text:'B'}],undefined,'above'));assert.throws(()=>parseVisual({kind:'geometry',shape:'cube',alt:'A'}));
});
test('secondary presets support table/tally/pictograph, unequal fractions, pot groups, all vessels and explicit labels',()=>{
 const variants=[...['table','tally','pictograph'].map(mode=>({kind:'data',mode,unitValue:1,rows:[{label:'Elma',value:3}]})),...['rectangle','bar'].map(model=>({kind:'fraction',model,parts:[1,2,1],shaded:[1]})),{kind:'groups',objectType:'flower',totalObjects:21,objectsPerGroup:3,arrangement:'pots'},{kind:'math-cards',mode:'tokens',items:[{shape:'triangle',value:21},{shape:'circle',value:null}]},{kind:'rotation',direction:'counterclockwise',quarterTurns:2,startIndex:0,labels:[1,2,3,4]},...['glass','bottle','jug','bucket','spoon','ladle','cup','pot'].map(vessel=>({kind:'container',vessel,capacityClass:'medium',fill:.5})),{kind:'ruler',maxCm:10,startCm:0,endCm:4,objectType:'book',showLength:true}];for(const v of variants)assert.deepEqual(parseVisual({...v,alt:'Verilen model'}),{...v,alt:'Verilen model'});
});
test('shared stimulus resolves into separate safe immutable presentations, never a shared award key',()=>{const a=present(source.questions[18]),b=present(source.questions[29]);assert.deepEqual(a.visual,b.visual);assert.equal(a.visual.stimulusId,'wheel');assert.notEqual(source.questions[18].id,source.questions[29].id);assert.throws(()=>resolveStimulus(undefined,'missing',source.stimuli));assert.throws(()=>resolveStimulus(a.visual,'wheel',source.stimuli));assert.throws(()=>resolveStimulus(undefined,'constructor',source.stimuli));});
test('import adapter supports three choices, placement and shared stimuli without modifying real pilot records',()=>{
 const root=resolve('artifacts/visual-engine'),temp=mkdtempSync(join(root,'schema-'));
 try{cpSync('data',temp,{recursive:true});const p=join(temp,'soru-bankasi/2-sinif/matematik.json'),b=JSON.parse(readFileSync(p));b.stimuli=source.stimuli;b.questions[0].stimulusId='wheel';b.questions[0].visualPlacement='above';b.questions[0].options=b.questions[0].options.slice(0,3);b.questions[0].correctOptionId='a';writeFileSync(p,JSON.stringify(b));const imported=loadCurriculumBank(temp).records.find(r=>r.question.questionId===b.questions[0].id);assert.equal(imported.question.choices.length,3);assert.equal(imported.question.visual.stimulusId,'wheel');assert.equal(imported.question.visualPlacement,'above');b.stimuli.wheel.url='https://invalid.example';writeFileSync(p,JSON.stringify(b));assert.throws(()=>loadCurriculumBank(temp));}finally{if(!resolve(temp).startsWith(root+sep))throw new Error('Unsafe cleanup');rmSync(temp,{recursive:true,force:true});}
 assert.equal(loadCurriculumBank().records.length,130);
});
test('server DTO retains all presets and shared stimulus after shuffle and resume without private keys',async()=>{const t=await pupilClient.call('startTest',fixture.params);assert.equal(t.questions.length,30);for(const q of t.questions){const raw=fixture.records.find(r=>r.question.questionId===q.questionId).question;assert.deepEqual(q.visual,raw.visual);assert.deepEqual(q.visualPlacement,raw.visualPlacement);for(const c of q.choices)assert.deepEqual(c,raw.choices.find(x=>x.choiceId===c.choiceId));}assert.deepEqual((await pupilClient.call('getTestSession',{testSessionId:t.testSessionId})).questions,t.questions);for(const key of ['correctChoiceId','correctOptionId','explanation','computedResult'])assert.equal(JSON.stringify(t).includes(key),false);});
test('all presets use secure first-answer and first-correct XP; shared stimulus questions award independently',async()=>{
 let t=await pupilClient.call('startTest',fixture.params);const wrong=t.questions[0];let a=await pupilClient.call('submitAnswer',{testSessionId:t.testSessionId,questionId:wrong.questionId,selectedChoiceId:'b'});assert.equal(a.answer.earnedXP,0);assert.equal((await pupilClient.call('submitAnswer',{testSessionId:t.testSessionId,questionId:wrong.questionId,selectedChoiceId:'a'})).answer.isCorrect,false);
 for(const q of t.questions.slice(1))a=await pupilClient.call('submitAnswer',{testSessionId:t.testSessionId,questionId:q.questionId,selectedChoiceId:'a'});assert.equal(a.totalXP,29);
 t=await pupilClient.call('startTest',fixture.params);for(const q of t.questions){const replies=await Promise.all(Array.from({length:fixture.records.find(r=>r.question.questionId===q.questionId).question.visual?.stimulusId?3:1},()=>pupilClient.call('submitAnswer',{testSessionId:t.testSessionId,questionId:q.questionId,selectedChoiceId:'a'})));assert.ok(replies.every(r=>r.answer.earnedXP===(q.questionId===wrong.questionId?1:0)));}
 const report=await owner.call('teacherAnalytics',{studentId:student.studentId});assert.equal(report.totals.academicXP,30);assert.deepEqual(report.totals.overall,{solved:60,correct:59,wrong:1});const awards=await fixture.db.collection(`teachers/${owner.auth.currentUser.uid}/students/${student.studentId}/awardedQuestions`).get();assert.equal(awards.size,30);
});
test('malformed nested scene cannot create a test; foreign teacher/student and forged visual answers stay denied',async()=>{
 const r=fixture.records[0],ref=fixture.db.doc('questions/'+r.question.questionId);await ref.update({visual:{kind:'scene',preset:'stack',alt:'Sahne',items:[{kind:'objects',objectType:'pencil',count:1000,layout:'grid',alt:'Nesneler'}]}});try{await assert.rejects(pupilClient.call('startTest',fixture.params));}finally{await ref.set(r.question);}
 const t=await pupilClient.call('startTest',fixture.params);await assert.rejects(foreign.call('getTestSession',{testSessionId:t.testSessionId}));await assert.rejects(pupilClient.call('submitAnswer',{testSessionId:t.testSessionId,questionId:t.questions[0].questionId,visual:{kind:'clock',hour:2,minute:30,alt:'Saat'}}));
 const cls=await foreign.call('createClass',{className:'Foreign',defaultGradeLevel:2}),s=await foreign.call('createStudent',{classId:cls.classId,firstName:'Başka',lastName:'Öğrenci',gradeLevel:2}),c=client();try{await loginStudent(c,s.code);await assert.rejects(c.call('getTestSession',{testSessionId:t.testSessionId}));}finally{await c.close();}
});
