import {test} from 'node:test';import assert from 'node:assert/strict';import {readFileSync,readdirSync,writeFileSync,unlinkSync,existsSync} from 'node:fs';import {randomUUID} from 'node:crypto';import {initializeApp,getApps,deleteApp} from 'firebase-admin/app';import {getFirestore} from 'firebase-admin/firestore';import {getAuth} from 'firebase-admin/auth';import {client,teacherClient,loginStudent} from './helpers.mjs';import {importQuestionFolder} from '../scripts/import-question-folder.mjs';
process.env.FIRESTORE_EMULATOR_HOST='127.0.0.1:8080';process.env.FIREBASE_AUTH_EMULATOR_HOST='127.0.0.1:9099';process.env.GCLOUD_PROJECT='demo-test-arena';
test('prepared sync updates live catalog and quiz: wrong 0, first correct 1, repeated correct 0',async()=>{
 const app=initializeApp({projectId:'demo-test-arena'},'sync-quiz-test'),db=getFirestore(app),marker='zz-sync-quiz-'+randomUUID().slice(0,8),file='data/questions/'+marker+'.json',bank=JSON.parse(readFileSync('data/questions/'+readdirSync('data/questions').find(f=>f.startsWith('2-sinif-ingilizce')),'utf8'));bank.questions.forEach((q,i)=>q.id=marker+'-'+i);let teacher,pupil,uid;const keys=new Map(bank.questions.map(q=>[q.id,q.correctOptionId])),testIds=[];
 try{writeFileSync(file,JSON.stringify(bank));const synced=await importQuestionFolder({log:()=>{}});assert.equal(synced.imported,10);teacher=await teacherClient({fixtures:false});uid=teacher.auth.currentUser.uid;const cls=await teacher.call('createClass',{className:'Disposable sync test',defaultGradeLevel:2}),student=await teacher.call('createStudent',{classId:cls.classId,firstName:'Sync',lastName:'Test',gradeLevel:2});pupil=client();await loginStudent(pupil,student.code);
 const catalog=await pupil.call('quizCatalog',{}),subject=catalog.curricula.find(c=>c.grade===2).subjects.find(s=>s.id==='ingilizce');assert.equal(subject.count,70);const unit=subject.units.find(u=>u.id===bank.questions[0].unitId),topic=unit.topics.find(t=>t.id===bank.questions[0].topicId),packs=subject.navigationModel==='theme-test'?unit.packs:topic.packs;
 const params={grade:2,subjectId:'ingilizce',unitId:unit.id,...(subject.navigationModel==='theme-test'?{}:{topicId:topic.id}),packId:packs.at(-1).id};const t=await pupil.call('startTest',params);testIds.push(t.testSessionId);assert(t.questions.every(q=>keys.has(q.questionId)));for(const q of t.questions){assert(!('correctOptionId' in q));assert(!('correctChoiceId' in q));assert(!('explanation' in q));}
 const [wrong,right]=t.questions;const r0=await pupil.call('submitAnswer',{testSessionId:t.testSessionId,questionId:wrong.questionId,selectedChoiceId:wrong.choices.find(c=>c.choiceId!==keys.get(wrong.questionId)).choiceId});assert.equal(r0.answer.earnedXP,0);
 const r1=await pupil.call('submitAnswer',{testSessionId:t.testSessionId,questionId:right.questionId,selectedChoiceId:keys.get(right.questionId)});assert.equal(r1.answer.earnedXP,1);
 const t2=await pupil.call('startTest',params);testIds.push(t2.testSessionId);const r2=await pupil.call('submitAnswer',{testSessionId:t2.testSessionId,questionId:right.questionId,selectedChoiceId:keys.get(right.questionId)});assert.equal(r2.answer.earnedXP,0);
 unlinkSync(file);await importQuestionFolder({log:()=>{}});assert.equal((await pupil.call('quizCatalog',{})).curricula.find(c=>c.grade===2).subjects.find(s=>s.id==='ingilizce').count,60);
 }finally{if(existsSync(file))unlinkSync(file);await importQuestionFolder({log:()=>{}});for(const id of testIds)await db.doc('privateTestKeys/'+id).delete();if(uid){for(const col of ['studentSessions','studentCodeIndex']){const docs=await db.collection(col).where('teacherUid','==',uid).get();for(const d of docs.docs){if(col==='studentSessions')await getAuth(app).deleteUser(d.id).catch(()=>{});await d.ref.delete();}}await db.recursiveDelete(db.doc('teachers/'+uid));await getAuth(app).deleteUser(uid);}await teacher?.close();await pupil?.close();await Promise.all(getApps().filter(a=>['sync-quiz-test','prepared-bank-import'].includes(a.name)).map(deleteApp));}
});
