import {test} from 'node:test';import assert from 'node:assert/strict';
import {readFileSync,writeFileSync,unlinkSync,readdirSync,existsSync} from 'node:fs';import {randomUUID,createHash} from 'node:crypto';
import {initializeApp,getApps,deleteApp} from 'firebase-admin/app';import {getFirestore} from 'firebase-admin/firestore';import {getAuth} from 'firebase-admin/auth';
import {chromium,expect as baseExpect} from '@playwright/test';import {assertLocalSync,importQuestionFolder} from '../scripts/import-question-folder.mjs';import {prepareQuestionBank} from '../scripts/curriculum-bank.mjs';
process.env.FIRESTORE_EMULATOR_HOST='127.0.0.1:8080';process.env.FIREBASE_AUTH_EMULATOR_HOST='127.0.0.1:9099';process.env.GCLOUD_PROJECT='demo-test-arena';
const source=JSON.parse(readFileSync('data/questions/'+readdirSync('data/questions').find(f=>f.startsWith('2-sinif-ingilizce')),'utf8'));
const hash=x=>createHash('sha256').update(JSON.stringify(x)).digest('hex');
test('local guard rejects missing emulator, live project and arbitrary path',async()=>{for(const [key,value]of [['FIRESTORE_EMULATOR_HOST',''],['FIRESTORE_EMULATOR_HOST','example.com:8080'],['GCLOUD_PROJECT','production']]){const old=process.env[key];process.env[key]=value;assert.throws(assertLocalSync);process.env[key]=old;}await assert.rejects(importQuestionFolder({folder:'.firebase'}),/fixed/);});
test('schema retains public/private split and rejects wrong answers',()=>{const p=prepareQuestionBank(source);assert(!('correctOptionId' in p.records[0].question));assert(!('explanation' in p.records[0].question));const b=structuredClone(source);b.questions[0].correctOptionId='missing';assert.throws(()=>prepareQuestionBank(b));});
test('shared sync adds/removes 10, preserves unrelated data, refuses malformed source and immutable ID conflicts',async()=>{
 const app=initializeApp({projectId:'demo-test-arena'},'sync-test'),db=getFirestore(app),marker='sync-test-'+randomUUID().slice(0,8),path='data/questions/'+marker+'.json',broken='data/questions/'+marker+'-bad.json',manifest='data/questions/'+marker+'-meta';const b=structuredClone(source);b.questions.forEach((q,i)=>q.id=marker+'-'+i);const ids=b.questions.map(q=>q.id);const sync=()=>importQuestionFolder({log:()=>{}}),results={};
 const docs=async()=>{let values=[];async function walk(c){for(const d of(await c.get()).docs){if(!ids.includes(d.id))values.push([d.ref.path,d.data()]);for(const sub of await d.ref.listCollections())await walk(sub);}}for(const c of await db.listCollections())await walk(c);return hash(values.sort((a,b)=>a[0].localeCompare(b[0])));};const before=await docs();
 const unmanaged=marker+'-unmanaged';await db.doc('questions/'+unmanaged).set({status:'draft',testOnly:true});
 try{
  results.baseline=await sync();assert.equal(results.baseline.failed,0);assert.equal(results.baseline.unchanged,300);
  writeFileSync(path,JSON.stringify(b));results.add=await sync();assert.equal(results.add.imported,10);for(const id of ids){assert((await db.doc('questions/'+id).get()).exists);assert((await db.doc('privateQuestionAnswers/'+id).get()).exists);}
  const changed=structuredClone(b);changed.questions[0].question+=' test';writeFileSync(path,JSON.stringify(changed));results.conflict=await sync();assert.equal(results.conflict.conflicts,1);assert(results.conflict.deletionSkipped);assert.equal((await db.doc('questions/'+ids[0]).get()).data().questionText,b.questions[0].question);
  unlinkSync(path);writeFileSync(broken,'{invalid');results.broken=await sync();assert.equal(results.broken.failed,1);assert.equal(results.broken.removedQuestions,0);for(const id of ids)assert((await db.doc('questions/'+id).get()).exists);
  unlinkSync(broken);results.remove=await sync();assert.equal(results.remove.removedQuestions,10);assert.equal(results.remove.removedAnswers,10);
  writeFileSync(path,JSON.stringify(changed));results.reusedId=await sync();assert.equal(results.reusedId.conflicts,1);unlinkSync(path);await sync();assert((await db.doc('questions/'+unmanaged).get()).exists);
  writeFileSync('.firebase/question-bank-sync/sync.lock',String(process.pid));try{await assert.rejects(sync(),e=>e.code==='SYNC_BUSY');}finally{unlinkSync('.firebase/question-bank-sync/sync.lock');}
  for(const id of ids){assert(!(await db.doc('questions/'+id).get()).exists);assert(!(await db.doc('privateQuestionAnswers/'+id).get()).exists);}
  await db.doc('questions/'+unmanaged).delete();assert.equal(await docs(),before);writeFileSync('.firebase/question-bank-sync/test-results.json',JSON.stringify(results,null,2));
 }finally{for(const f of [path,broken])if(existsSync(f))unlinkSync(f);await sync();await db.doc('questions/'+unmanaged).delete();await Promise.all(getApps().filter(a=>['sync-test','prepared-bank-import'].includes(a.name)).map(deleteApp));}
});
test('normal teacher sees no admin UI and real backend rejects sync without writes',async()=>{
 const app=initializeApp({projectId:'demo-test-arena'},'normal-auth-test'),auth=getAuth(app),db=getFirestore(app),browser=await chromium.launch(),expect=baseExpect.configure({timeout:60000});let uid;
 try{const user=await auth.createUser({email:'sync-normal-'+randomUUID()+'@example.invalid',password:'temporary-test-only-password'});uid=user.uid;const context=await browser.newContext({viewport:{width:360,height:800}}),page=await context.newPage();await page.goto('http://127.0.0.1:5173/ogretmen-giris');await page.evaluate(async email=>{const f=await import('/src/data/firebase.ts'),a=await import('/node_modules/.vite/deps/firebase_auth.js');await a.signInWithEmailAndPassword(f.auth,email,'temporary-test-only-password');},user.email);await page.goto('http://127.0.0.1:5173/ogretmen');await expect(page.getByRole('heading',{name:'Merhaba, öğretmenim.'})).toBeVisible();assert.equal(await page.getByRole('button',{name:'Soru Bankasını Güncelle'}).count(),0);assert.equal(await page.getByText('Admin Araçları',{exact:true}).count(),0);const before=(await db.collection('questions').get()).size;const result=await page.evaluate(async()=>{const f=await import('/src/data/firebase.ts');try{await f.call('syncQuestionBank',{});return 'accepted';}catch(e){return e.code;}});assert.equal(result,'functions/permission-denied');assert.equal((await db.collection('questions').get()).size,before);await page.screenshot({path:'.firebase/sync-normal-360.png',fullPage:true});await context.close();}finally{if(uid)await auth.deleteUser(uid);await browser.close();await deleteApp(app);}
});
